/// Cross-SDK hash compatibility tests.
///
/// These tests verify that the Dart/Flutter [hashUser] function produces
/// identical results to the Java, Go, iOS (Swift), Android (Kotlin), and
/// Python SDK implementations for the same inputs.
///
/// Test vectors were generated by running the Python reference implementation:
///   hashlib.md5(f'{userId}:{flagKey}'.encode()).digest()[:4]
///   → struct.unpack('<I', ...)[0] / 4294967296.0
///
/// All other SDKs produce bit-identical output for these vectors.
import 'package:flutter_test/flutter_test.dart';
import 'package:experimently/experimently.dart';

void main() {
  group('hashUser — cross-SDK parity', () {
    // Tolerance: 1e-9 (well within double precision; differences only arise
    // if the wrong divisor or byte-order is used).
    const tol = 1e-9;

    test('user-123 : my-flag → 0.6927449859', () {
      expect(
        hashUser('user-123', 'my-flag'),
        closeTo(0.6927449859213, tol),
      );
    });

    test('user-456 : feature-x → 0.0776851554', () {
      expect(
        hashUser('user-456', 'feature-x'),
        closeTo(0.0776851554, tol),
      );
    });

    test('alice : dark-mode → 0.0353864399', () {
      expect(
        hashUser('alice', 'dark-mode'),
        closeTo(0.0353864399, tol),
      );
    });

    test('bob : new-checkout → 0.1463384565', () {
      expect(
        hashUser('bob', 'new-checkout'),
        closeTo(0.1463384565, tol),
      );
    });

    test('user-789 : beta-feature → 0.3134219283', () {
      expect(
        hashUser('user-789', 'beta-feature'),
        closeTo(0.3134219283, tol),
      );
    });

    test('test-user : flag-key → 0.9923393740', () {
      expect(
        hashUser('test-user', 'flag-key'),
        closeTo(0.9923393740, tol),
      );
    });

    test('empty userId : empty-user → 0.3582690393', () {
      expect(
        hashUser('', 'empty-user'),
        closeTo(0.3582690393, tol),
      );
    });

    test('a : b → 0.6056532171', () {
      expect(
        hashUser('a', 'b'),
        closeTo(0.6056532171, tol),
      );
    });
  });

  group('hashUser — divisor correctness', () {
    test('divisor is 2^32 (4294967296), not MaxUInt32 (4294967295)', () {
      // For any non-zero hash value, using 4294967295 as divisor would produce
      // a slightly *larger* result than 4294967296.
      // We verify this by checking the output is < 1.0 and matches the 2^32
      // formula precisely.
      //
      // user-123:my-flag → uint32 = 2975317059
      //   / 4294967296 = 0.69274498592130...   ← correct
      //   / 4294967295 = 0.69274498608230...   ← wrong (would differ at 9th decimal)
      final h = hashUser('user-123', 'my-flag');
      expect(h, lessThan(1.0));
      expect(h, greaterThanOrEqualTo(0.0));

      // The correct value at 15 significant figures:
      expect(h, closeTo(0.692744985921308, 1e-12));
    });

    test('hash is always in [0.0, 1.0)', () {
      final testCases = [
        ['user-0', 'flag-0'],
        ['user-max', 'flag-max'],
        ['unicode-\u00e9', 'flag'],
        ['spaces in name', 'flag with spaces'],
      ];
      for (final tc in testCases) {
        final h = hashUser(tc[0], tc[1]);
        expect(h, greaterThanOrEqualTo(0.0), reason: 'hash for ${tc[0]}:${tc[1]} < 0');
        expect(h, lessThan(1.0), reason: 'hash for ${tc[0]}:${tc[1]} >= 1');
      }
    });

    test('separator is colon — different from unsalted hashes', () {
      // "user-123my-flag" (no colon) must differ from "user-123:my-flag"
      final withColon = hashUser('user-123', 'my-flag');
      // Directly concatenated would give "user-123my-flag" as MD5 input;
      // we verify the colon-separated version is what we get.
      expect(withColon, closeTo(0.6927449859, 1e-7));
    });

    test('different (userId, flagKey) pairs produce different hashes', () {
      final h1 = hashUser('user-1', 'flag-a');
      final h2 = hashUser('user-2', 'flag-a');
      final h3 = hashUser('user-1', 'flag-b');
      expect(h1, isNot(closeTo(h2, 1e-10)));
      expect(h1, isNot(closeTo(h3, 1e-10)));
    });

    test('hash is deterministic — same inputs always produce same output', () {
      for (var i = 0; i < 20; i++) {
        expect(hashUser('user-abc', 'flag-xyz'),
            closeTo(hashUser('user-abc', 'flag-xyz'), 1e-15));
      }
    });

    test('little-endian byte order is used', () {
      // If big-endian were used, the hash for user-123:my-flag would differ.
      // The correct little-endian result is 0.6927449859.
      // Big-endian of the same 4 bytes would give a different value.
      // We simply confirm the known-good little-endian value.
      expect(hashUser('user-123', 'my-flag'), closeTo(0.6927449859, 1e-7));
    });
  });
}
