"""The public API does not change under anyone's feet: the OpenAPI snapshots.

``docs/api/openapi-v1.stable.json`` is the core API (the document a tree with
``modules/`` deleted serves) and ``docs/api/openapi-v1.full.json`` is the full
profile's.  Both are regenerated by ``make openapi`` and checked in; this
module regenerates them in a fresh interpreter (``backend.scripts.dump_openapi
--profile core|full``, so the result does not depend on what this test
session has loaded) and compares.

Rules
-----
* A path/method in the snapshot that is **stable** (no ``x-stability``, or
  any value other than ``beta``) must still exist and its operation object --
  parameters, request body, responses, and every component schema those
  reference, transitively -- must be identical.  Any difference fails.
* A path/method marked ``x-stability: beta`` may change or disappear; that
  produces a warning, not a failure.  Mark a route beta from the decorator::

      @router.get("/things", openapi_extra={"x-stability": "beta"})

* A path/method that exists but is not in the snapshot yet is a warning too:
  run ``make openapi`` and commit the result, and mark it beta unless it is
  meant to be stable from day one.
* The full document is a superset of the core one, and the module paths are
  exactly the list the dashboard's URL guard uses
  (``frontend/src/tests/fixtures/openapi.module-paths.json``), so the three
  fixtures cannot drift apart.

The full-profile comparison is ``@pytest.mark.modules``: in a core build
there is no full document to compare.
"""

from __future__ import annotations

import json
import os
import pathlib
import subprocess
import sys
import tempfile
import warnings
from typing import Any, Dict, Iterator, List, Set, Tuple

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
DOCS_API = REPO_ROOT / "docs" / "api"
STABLE_SNAPSHOT = DOCS_API / "openapi-v1.stable.json"
FULL_SNAPSHOT = DOCS_API / "openapi-v1.full.json"
MODULE_PATHS_FIXTURE = (
    REPO_ROOT / "frontend" / "src" / "tests" / "fixtures" / "openapi.module-paths.json"
)

HTTP_METHODS = ("get", "post", "put", "patch", "delete", "head", "options", "trace")
BETA = "beta"

pytestmark = pytest.mark.smoke


# ---------------------------------------------------------------------------
# Document plumbing
# ---------------------------------------------------------------------------


def dump_document(profile: str) -> Dict[str, Any]:
    """The live OpenAPI document for *profile*, from a fresh interpreter."""
    with tempfile.TemporaryDirectory() as tmp:
        output = pathlib.Path(tmp) / f"openapi-{profile}.json"
        env = {**os.environ, "APP_ENV": "test", "TESTING": "true"}
        env.pop("ENVIRONMENT", None)
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "backend.scripts.dump_openapi",
                "--profile",
                profile,
                "--full",
                str(output),
            ],
            cwd=REPO_ROOT,
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        assert result.returncode == 0, (
            f"dump_openapi --profile {profile} failed:\n{result.stderr[-4000:]}"
        )
        return json.loads(output.read_text(encoding="utf-8"))


def load_snapshot(path: pathlib.Path) -> Dict[str, Any]:
    assert path.exists(), (
        f"{path.relative_to(REPO_ROOT)} is missing; run `make openapi`"
    )
    return json.loads(path.read_text(encoding="utf-8"))


def _operations(document: Dict[str, Any]) -> Iterator[Tuple[str, str, Dict[str, Any]]]:
    for path, item in document.get("paths", {}).items():
        for method, operation in item.items():
            if method in HTTP_METHODS:
                yield path, method, operation


def _refs(node: Any, out: Set[str]) -> None:
    """Collect every ``#/components/schemas/<name>`` reference under *node*."""
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
            out.add(ref.rsplit("/", 1)[-1])
        for value in node.values():
            _refs(value, out)
    elif isinstance(node, list):
        for value in node:
            _refs(value, out)


def referenced_schemas(document: Dict[str, Any], operation: Dict[str, Any]) -> Set[str]:
    """Names of the component schemas *operation* reaches, transitively."""
    schemas = document.get("components", {}).get("schemas", {})
    pending: Set[str] = set()
    _refs(operation, pending)
    seen: Set[str] = set()
    while pending:
        name = pending.pop()
        if name in seen:
            continue
        seen.add(name)
        _refs(schemas.get(name), pending)
    return seen


def _differing_keys(a: Any, b: Any, prefix: str = "") -> List[str]:
    """Dotted keys at which two JSON values differ (first level of difference)."""
    if isinstance(a, dict) and isinstance(b, dict):
        out: List[str] = []
        for key in sorted(set(a) | set(b)):
            if key not in a:
                out.append(f"{prefix}{key} (added)")
            elif key not in b:
                out.append(f"{prefix}{key} (removed)")
            elif a[key] != b[key]:
                out.extend(_differing_keys(a[key], b[key], f"{prefix}{key}."))
        return out
    if isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
        out = []
        for index, (left, right) in enumerate(zip(a, b)):
            if left != right:
                out.extend(_differing_keys(left, right, f"{prefix}{index}."))
        return out
    return [prefix.rstrip(".") or "<root>"]


def is_beta(operation: Dict[str, Any]) -> bool:
    return operation.get("x-stability") == BETA


def compare(
    snapshot: Dict[str, Any], current: Dict[str, Any]
) -> Tuple[List[str], List[str]]:
    """Return ``(errors, warnings)`` for *current* against *snapshot*.

    Errors are changes to stable operations; warnings are changes to beta
    operations and operations the snapshot does not know yet.
    """
    errors: List[str] = []
    notes: List[str] = []
    current_paths = current.get("paths", {})
    snapshot_schemas = snapshot.get("components", {}).get("schemas", {})
    current_schemas = current.get("components", {}).get("schemas", {})

    for path, method, operation in _operations(snapshot):
        label = f"{method.upper()} {path}"
        bucket = notes if is_beta(operation) else errors
        live = current_paths.get(path, {}).get(method)
        if live is None:
            bucket.append(f"{label}: removed")
            continue
        if live != operation:
            keys = ", ".join(_differing_keys(operation, live)[:8])
            bucket.append(f"{label}: operation changed at {keys}")
        for name in sorted(referenced_schemas(snapshot, operation)):
            if name not in current_schemas:
                bucket.append(f"{label}: schema {name} removed")
            elif current_schemas[name] != snapshot_schemas.get(name):
                keys = ", ".join(
                    _differing_keys(snapshot_schemas.get(name), current_schemas[name])[
                        :8
                    ]
                )
                bucket.append(f"{label}: schema {name} changed at {keys}")

    snapshot_ops = {(p, m) for p, m, _ in _operations(snapshot)}
    for path, method, operation in _operations(current):
        if (path, method) not in snapshot_ops:
            stability = "beta" if is_beta(operation) else "stable"
            notes.append(
                f"{method.upper()} {path}: not in the snapshot yet ({stability}); "
                "run `make openapi`"
            )
    return errors, notes


def _report(title: str, lines: List[str]) -> str:
    return title + "\n  " + "\n  ".join(lines)


def _warn_all(prefix: str, notes: List[str]) -> None:
    for note in notes:
        warnings.warn(f"{prefix}: {note}", UserWarning, stacklevel=2)


# ---------------------------------------------------------------------------
# The comparison logic itself, on synthetic documents (so the beta rule is
# exercised even while no route in the tree carries x-stability)
# ---------------------------------------------------------------------------


def _doc(
    paths: Dict[str, Any], schemas: Dict[str, Any] | None = None
) -> Dict[str, Any]:
    return {"paths": paths, "components": {"schemas": schemas or {}}}


def test_compare_flags_changes_to_stable_operations_as_errors():
    snapshot = _doc(
        {"/a": {"get": {"responses": {"200": {"$ref": "#/components/schemas/A"}}}}},
        {"A": {"type": "object", "properties": {"x": {"type": "string"}}}},
    )
    same = json.loads(json.dumps(snapshot))
    assert compare(snapshot, same) == ([], [])

    removed = _doc({})
    errors, notes = compare(snapshot, removed)
    assert errors == ["GET /a: removed"] and notes == []

    changed = json.loads(json.dumps(snapshot))
    changed["paths"]["/a"]["get"]["parameters"] = [{"name": "q", "in": "query"}]
    errors, _ = compare(snapshot, changed)
    assert errors == ["GET /a: operation changed at parameters (added)"]

    schema_changed = json.loads(json.dumps(snapshot))
    schema_changed["components"]["schemas"]["A"]["properties"]["x"] = {
        "type": "integer"
    }
    errors, _ = compare(snapshot, schema_changed)
    assert errors == ["GET /a: schema A changed at properties.x.type"]


def test_compare_flags_changes_to_beta_operations_as_warnings_only():
    snapshot = _doc({"/b": {"post": {"x-stability": "beta", "responses": {}}}})
    errors, notes = compare(snapshot, _doc({}))
    assert errors == [] and notes == ["POST /b: removed"]

    changed = _doc({"/b": {"post": {"x-stability": "beta", "responses": {"201": {}}}}})
    errors, notes = compare(snapshot, changed)
    assert errors == [] and notes == [
        "POST /b: operation changed at responses.201 (added)"
    ]


def test_compare_reports_unsnapshotted_operations_as_warnings():
    snapshot = _doc({})
    errors, notes = compare(snapshot, _doc({"/c": {"get": {"responses": {}}}}))
    assert errors == []
    assert notes == ["GET /c: not in the snapshot yet (stable); run `make openapi`"]


def test_referenced_schemas_is_transitive():
    document = _doc(
        {},
        {
            "A": {"properties": {"b": {"$ref": "#/components/schemas/B"}}},
            "B": {"items": {"$ref": "#/components/schemas/C"}},
            "C": {"type": "string"},
            "Unrelated": {"type": "string"},
        },
    )
    operation = {"responses": {"200": {"$ref": "#/components/schemas/A"}}}
    assert referenced_schemas(document, operation) == {"A", "B", "C"}


# ---------------------------------------------------------------------------
# The snapshots against the tree
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def stable_snapshot() -> Dict[str, Any]:
    return load_snapshot(STABLE_SNAPSHOT)


@pytest.fixture(scope="module")
def full_snapshot() -> Dict[str, Any]:
    return load_snapshot(FULL_SNAPSHOT)


@pytest.fixture(scope="module")
def core_document() -> Dict[str, Any]:
    return dump_document("core")


def test_snapshots_are_well_formed(stable_snapshot, full_snapshot):
    for name, document in (("stable", stable_snapshot), ("full", full_snapshot)):
        assert document.get("openapi", "").startswith("3."), (
            f"{name}: not an OpenAPI 3 document"
        )
        assert document.get("paths"), f"{name}: no paths"
        assert "components" in document, f"{name}: no components (dump with --full)"
        for path, _method, operation in _operations(document):
            stability = operation.get("x-stability")
            assert stability in (None, BETA, "stable"), (
                f"{name}: {path} has x-stability={stability!r}; only 'beta' means anything"
            )


def test_core_api_matches_stable_snapshot(stable_snapshot, core_document):
    errors, notes = compare(stable_snapshot, core_document)
    _warn_all("openapi-v1.stable.json", notes)
    assert not errors, _report(
        "The core API changed under a stable path. A stable route may not "
        "change shape; add a new route (mark it x-stability: beta while it "
        "settles) or bump the API version. If the change is intended, "
        "regenerate with `make openapi` and say so in the pull request:",
        errors,
    )


def test_stable_snapshot_is_a_subset_of_the_full_snapshot(
    stable_snapshot, full_snapshot
):
    """Every core operation exists, unchanged, in the full document."""
    errors, _notes = compare(stable_snapshot, full_snapshot)
    assert not errors, _report(
        "openapi-v1.full.json is not a superset of openapi-v1.stable.json "
        "(regenerate both with `make openapi`):",
        errors,
    )


def test_module_paths_match_the_dashboard_fixture(stable_snapshot, full_snapshot):
    """``full - stable`` is exactly what the URL guard treats as a module's."""
    module_paths = set(full_snapshot["paths"]) - set(stable_snapshot["paths"])
    fixture = json.loads(MODULE_PATHS_FIXTURE.read_text(encoding="utf-8"))
    listed = set(fixture["paths"])
    assert module_paths == listed, (
        "frontend/src/tests/fixtures/openapi.module-paths.json disagrees with the "
        f"two snapshots.\n  only in the snapshots: {sorted(module_paths - listed)}"
        f"\n  only in the fixture: {sorted(listed - module_paths)}"
    )


@pytest.mark.modules
def test_full_api_matches_full_snapshot(full_snapshot):
    document = dump_document("full")
    errors, notes = compare(full_snapshot, document)
    _warn_all("openapi-v1.full.json", notes)
    assert not errors, _report(
        "The full-profile API changed under a stable path (see "
        "test_core_api_matches_stable_snapshot for the rule; regenerate with "
        "`make openapi` if intended):",
        errors,
    )
