"""A connection to a customer's data warehouse, for warehouse analysis (#312).

One row per warehouse an ADMIN has connected.  The row holds what the
platform needs to reach the warehouse and nothing it could return to anyone:

* the non-secret parameters of the connection (``parameters``: the Snowflake
  account, user, role and warehouse; the BigQuery billing project, location
  and service-account e-mail; the Athena region, role ARN, workgroup and
  database), validated by the request schemas before they are stored;
* the credential, only ever as a Fernet token produced by
  :mod:`modules.backend.app.core.credential_crypto` under the operator's
  ``WAREHOUSE_CREDENTIALS_KEYS`` (``credentials_ciphertext``), and a second
  token for a key pair that has been generated but not yet confirmed by a
  passing test (``pending_credentials_ciphertext``).  Athena stores no secret;
* the limits every query and every day of queries is held to.

Deleting a connection deletes the row (there is no soft delete); its sources
go with it, and its runs keep their own copy of its name and type.

The table replaces an earlier ``warehouse_connections`` of a different shape,
which ``modules_0002_warehouse_analysis`` removes together with its rows.
"""

from __future__ import annotations

from typing import Optional

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Column,
    ForeignKey,
    Integer,
    LargeBinary,
    String,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.ext.declarative import declared_attr

from backend.app.core.database_config import get_schema_name
from backend.app.models.base import Base, BaseModel
from modules.backend.app.core import credential_crypto

#: Every warehouse type a connection may name.  Whether a type may be *used*
#: on a deployment is decided elsewhere; this is only what the table accepts.
WAREHOUSE_TYPES: tuple[str, ...] = ("bigquery", "snowflake", "athena")

#: The types whose queries are capped in bytes; Snowflake is capped in time.
BYTE_CAPPED_TYPES: tuple[str, ...] = ("bigquery", "athena")

#: Defaults and lower bounds (the upper bounds are operator settings).
DEFAULT_QUERY_TIMEOUT_SECONDS = 300
MIN_QUERY_TIMEOUT_SECONDS = 10
DEFAULT_MAX_RUNS_PER_DAY = 20
MIN_MAX_RUNS_PER_DAY = 1
#: The smallest per-query byte cap Athena's workgroup cutoff accepts.
MIN_MAX_BYTES_PER_QUERY = 10_000_000


def _in(column: str, values: tuple[str, ...]) -> str:
    return f"{column} IN ({', '.join(repr(v) for v in values)})"


class WarehouseConnection(Base, BaseModel):
    """A customer warehouse the platform may run analysis queries against."""

    __tablename__ = "warehouse_connections"

    name = Column(String(200), nullable=False)
    warehouse_type = Column(String(20), nullable=False)
    #: Non-secret connection parameters, per warehouse type.
    parameters = Column(JSONB, nullable=False, default=dict)
    #: The credential as a Fernet token; never a plaintext or encoded secret.
    credentials_ciphertext = Column(LargeBinary, nullable=True)
    #: A generated key pair awaiting its first passing connection test.
    pending_credentials_ciphertext = Column(LargeBinary, nullable=True)
    #: ``SHA256:<base64>`` of the Snowflake public key in use, and of the
    #: pending one.
    public_key_fingerprint = Column(String(100), nullable=True)
    pending_public_key_fingerprint = Column(String(100), nullable=True)
    #: Generated by the platform for Athena (``exp-`` and 32 hex characters).
    external_id = Column(String(64), nullable=True)
    query_timeout_seconds = Column(
        Integer, nullable=False, default=DEFAULT_QUERY_TIMEOUT_SECONDS
    )
    max_bytes_per_query = Column(BigInteger, nullable=True)
    max_runs_per_day = Column(Integer, nullable=False, default=DEFAULT_MAX_RUNS_PER_DAY)
    created_by = Column(
        UUID(as_uuid=True),
        ForeignKey(f"{get_schema_name()}.users.id", ondelete="SET NULL"),
        nullable=True,
    )

    @declared_attr
    def __table_args__(cls):
        return (
            UniqueConstraint(
                "external_id", name="uq_warehouse_connections_external_id"
            ),
            CheckConstraint(
                _in("warehouse_type", WAREHOUSE_TYPES),
                name="ck_warehouse_connections_type",
            ),
            # JSONB would otherwise store Python None as the JSON value null.
            CheckConstraint(
                "jsonb_typeof(parameters) = 'object'",
                name="ck_warehouse_connections_parameters_object",
            ),
            CheckConstraint(
                f"query_timeout_seconds >= {MIN_QUERY_TIMEOUT_SECONDS}",
                name="ck_warehouse_connections_query_timeout",
            ),
            CheckConstraint(
                f"max_runs_per_day >= {MIN_MAX_RUNS_PER_DAY}",
                name="ck_warehouse_connections_max_runs_per_day",
            ),
            # A byte cap exactly where the warehouse is capped in bytes.
            CheckConstraint(
                f"({_in('warehouse_type', BYTE_CAPPED_TYPES)}) = "
                "(max_bytes_per_query IS NOT NULL)",
                name="ck_warehouse_connections_byte_cap_type",
            ),
            CheckConstraint(
                "max_bytes_per_query IS NULL OR "
                f"max_bytes_per_query >= {MIN_MAX_BYTES_PER_QUERY}",
                name="ck_warehouse_connections_byte_cap_min",
            ),
            # Athena authenticates by role, with an external id, and stores
            # no secret; the others store one and have no external id.
            CheckConstraint(
                "(warehouse_type = 'athena') = (external_id IS NOT NULL)",
                name="ck_warehouse_connections_external_id",
            ),
            CheckConstraint(
                "warehouse_type <> 'athena' OR (credentials_ciphertext IS NULL "
                "AND pending_credentials_ciphertext IS NULL)",
                name="ck_warehouse_connections_athena_no_secret",
            ),
            {"schema": get_schema_name()},
        )

    # -- credentials ---------------------------------------------------------
    # The only way a credential is written to or read from this row: through
    # the operator's keys.  ``keys`` overrides the setting, for the rotation
    # command and tests that hold the keys themselves.

    def set_credentials(
        self, plaintext: bytes, *, pending: bool = False, keys: Optional[str] = None
    ) -> None:
        """Encrypt *plaintext* and store it as the current or the pending credential.

        Raises ``CredentialKeysUnavailable`` when no keys are configured; nothing
        is stored then.
        """
        if self.warehouse_type == "athena":
            raise ValueError("an Athena connection stores no credential")
        token = credential_crypto.encrypt(plaintext, keys=keys)
        if pending:
            self.pending_credentials_ciphertext = token
        else:
            self.credentials_ciphertext = token

    def get_credentials(
        self, *, pending: bool = False, keys: Optional[str] = None
    ) -> Optional[bytes]:
        """The stored credential's plaintext, or None when there is none.

        Raises ``CredentialUndecryptable`` when no configured key opens it and
        ``CredentialKeysUnavailable`` when no keys are configured.
        """
        token = (
            self.pending_credentials_ciphertext
            if pending
            else self.credentials_ciphertext
        )
        if token is None:
            return None
        return credential_crypto.decrypt(bytes(token), keys=keys)

    def __repr__(self) -> str:
        # Never the parameters or the credentials.
        return f"<WarehouseConnection id={self.id} type={self.warehouse_type!r}>"
