WITH events AS (
  SELECT CAST("USER_ID" AS VARCHAR) AS unit_id, CAST("EVENT_AT" AS TIMESTAMP_TZ) AS event_at, CAST("AMOUNT" AS DOUBLE) AS metric_value
  FROM "ANALYTICS"."PUBLIC"."ORDERS"
  WHERE CAST("EVENT_AT" AS TIMESTAMP_TZ) >= '2026-09-01 00:00:00 +00:00'::TIMESTAMP_TZ
    AND CAST("EVENT_AT" AS TIMESTAMP_TZ) < '2026-09-27 12:30:00 +00:00'::TIMESTAMP_TZ
    AND "STATUS" = 'paid'
    AND "IS_TEST" <> TRUE
    AND "AMOUNT" IS NOT NULL
)
SELECT COUNT(*) AS total_rows,
  COUNT(CASE WHEN unit_id IS NULL THEN 1 END) AS null_unit_rows,
  COUNT(CASE WHEN metric_value IS NULL THEN 1 END) AS null_value_rows,
  MIN(DATE_PART(EPOCH_SECOND, event_at)) AS earliest,
  MAX(DATE_PART(EPOCH_SECOND, event_at)) AS latest,
  MIN(TO_CHAR(CURRENT_TIMESTAMP(), 'TZH:TZM')) AS session_offset
FROM events
