#!/usr/bin/env node
/**
 * Generate nginx `location` blocks for the dynamic routes of the static export.
 *
 * `next build` with `output: 'export'` writes one HTML file per page, including
 * the dynamic ones (`out/experiments/[id].html`, `out/results/[id].html`, ...).
 * nginx knows nothing about Next's routing, so `/results/abc` would 404 (or, with
 * a naive `try_files ... /index.html` fallback, render the wrong page). This script
 * reads `.next/routes-manifest.json` — the routing table Next itself uses — and
 * emits one regex `location` per dynamic route that serves the matching
 * `[param].html` file, while still letting a static page with the same prefix win
 * (`/experiments/new` -> `experiments/new.html`, not `[id].html`).
 *
 * Usage (run after `next build`, from the frontend directory):
 *
 *   node scripts/nginx-routes.mjs                # writes out/../nginx/routes.conf
 *   node scripts/nginx-routes.mjs --out path.conf
 *   node scripts/nginx-routes.mjs --check         # print, do not write
 *
 * The generated file is included by frontend/nginx.conf (`include /etc/nginx/experimently-routes.conf;`).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const frontendDir = resolve(here, '..');

const args = process.argv.slice(2);
const argValue = (flag, fallback) => {
  const i = args.indexOf(flag);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
};
const manifestPath = resolve(argValue('--manifest', join(frontendDir, '.next', 'routes-manifest.json')));
const outDir = resolve(argValue('--export-dir', join(frontendDir, 'out')));
const outputPath = resolve(argValue('--out', join(frontendDir, 'nginx', 'routes.conf')));
const checkOnly = args.includes('--check');

if (!existsSync(manifestPath)) {
  console.error(`nginx-routes: ${manifestPath} not found — run \`next build\` first.`);
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const basePath = manifest.basePath || '';
const dynamicRoutes = manifest.dynamicRoutes || [];

/**
 * Turn a Next `regex` (`^/experiments/([^/]+?)(?:/)?$`) into an nginx PCRE
 * location regex. Next already escapes `-` and `/` is not special in PCRE,
 * so the expression is usable as-is; the optional trailing slash is kept.
 */
function toNginxRegex(routeRegex) {
  return routeRegex;
}

/** `/experiments/[id]` -> `/experiments/[id].html` (the exported file name). */
function pageFile(page) {
  return `${page}.html`;
}

const blocks = [];
const skipped = [];

for (const route of dynamicRoutes) {
  const file = pageFile(route.page);
  const exported = join(outDir, file);
  if (!existsSync(exported)) {
    // Catch-all routes with `getStaticPaths` (e.g. /docs/[...slug] with
    // fallback: false) are fully pre-rendered and have no `[...slug].html`;
    // the plain try_files in nginx.conf serves those.
    skipped.push({ page: route.page, reason: `${file} not in export` });
    continue;
  }
  const regex = toNginxRegex(route.regex);
  blocks.push(
    [
      `# ${route.page}`,
      `location ~ "${basePath}${regex}" {`,
      `    try_files $uri $uri.html "${basePath}${file}" =404;`,
      `}`,
    ].join('\n'),
  );
}

const header = [
  '# Generated by frontend/scripts/nginx-routes.mjs from .next/routes-manifest.json.',
  '# Dynamic Next.js routes -> exported [param].html files. Do not edit by hand.',
  `# routes: ${blocks.length} dynamic, ${skipped.length} pre-rendered/skipped`,
  '',
];

const content = header.concat(blocks).join('\n') + '\n';

if (checkOnly) {
  process.stdout.write(content);
} else {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
  console.log(`nginx-routes: wrote ${blocks.length} location block(s) to ${outputPath}`);
}
for (const s of skipped) {
  console.log(`nginx-routes: skipped ${s.page} (${s.reason})`);
}
