"""
Bring a PostgreSQL database up to the current schema.

Two situations are handled:

* **Existing database** (has an ``alembic_version`` table): run
  ``alembic upgrade head`` so pending incremental migrations are applied.

* **Fresh database** (no ``alembic_version`` table): create the schema from
  the SQLAlchemy models with ``Base.metadata.create_all`` and then
  ``alembic stamp head``.

In both cases, when the ``users`` table is empty afterwards, the first
administrator is created from ``FIRST_SUPERUSER`` / ``FIRST_SUPERUSER_PASSWORD``
(role ADMIN, superuser, bcrypt ``hashed_password``) so a fresh deployment can
sign in with ``AUTH_PROVIDER=local`` without running a seed script.  This is the pattern recommended in the Alembic
  cookbook ("Building an Up to Date Database from Scratch").  It is used
  because the historical migration chain in ``migrations/versions`` was
  autogenerated against databases that already had tables and cannot be
  replayed from zero (several revisions re-create tables that earlier
  revisions already created).  The models are the source of truth for the
  schema, exactly as they are for the test suite.

Usage (from the repository root)::

    python -m backend.app.db.bootstrap

Connection settings come from the usual ``POSTGRES_*`` environment
variables (``POSTGRES_SERVER``/``POSTGRES_HOST``, ``POSTGRES_PORT``,
``POSTGRES_USER``, ``POSTGRES_PASSWORD``, ``POSTGRES_DB``,
``POSTGRES_SCHEMA``).
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import Engine
from sqlalchemy.schema import CreateSchema

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parents[3]
_ALEMBIC_INI = _REPO_ROOT / "backend" / "app" / "db" / "alembic.ini"
_MIGRATIONS_DIR = _REPO_ROOT / "backend" / "app" / "db" / "migrations"


def database_url() -> str:
    """Build a SQLAlchemy URL from the POSTGRES_* environment variables."""
    user = os.environ.get("POSTGRES_USER", "postgres")
    password = os.environ.get("POSTGRES_PASSWORD", "postgres")
    host = (
        os.environ.get("POSTGRES_SERVER")
        or os.environ.get("POSTGRES_HOST")
        or "localhost"
    )
    port = os.environ.get("POSTGRES_PORT", "5432")
    db = os.environ.get("POSTGRES_DB", "experimentation")
    return f"postgresql://{user}:{password}@{host}:{port}/{db}"


def schema_name() -> str:
    """Schema the application tables live in.

    ``POSTGRES_SCHEMA`` wins when set (this is what alembic's env.py uses);
    otherwise fall back to the application's own environment-derived choice
    so the bootstrap and the running app agree.
    """
    explicit = os.environ.get("POSTGRES_SCHEMA")
    if explicit:
        return explicit
    from backend.app.core.database_config import get_schema_name

    return get_schema_name()


def alembic_config() -> Config:
    """Alembic config that works regardless of the current working directory."""
    cfg = Config(str(_ALEMBIC_INI))
    cfg.set_main_option("script_location", str(_MIGRATIONS_DIR))
    return cfg


def ensure_schema(engine: Engine, schema: str) -> None:
    with engine.begin() as conn:
        conn.execute(CreateSchema(schema, if_not_exists=True))


def has_alembic_version(engine: Engine, schema: str) -> bool:
    return inspect(engine).has_table("alembic_version", schema=schema)


def _point_models_at_schema(schema: str):
    """Import every model and point all tables at *schema*; return ``Base``."""
    # Open-core seam: register the Community models explicitly, then let the
    # Enterprise package add its own through hooks.register_model_module().
    # A Community build has no `ee` package and creates the 37 CE tables only.
    from backend.app.ee_loader import require_enterprise_or_absent
    from backend.app.models import register_core_models

    Base = register_core_models()
    # Strict: a fresh database built while the Enterprise registration is
    # broken would be missing the tables the Enterprise routers need.
    require_enterprise_or_absent()

    # (models.base.set_schema does the same, but derives the name from APP_ENV
    # rather than POSTGRES_SCHEMA.)
    Base.metadata.schema = schema
    for table in Base.metadata.tables.values():
        table.schema = schema
    return Base


def create_from_models(engine: Engine, schema: str) -> None:
    """Create every table defined by the SQLAlchemy models inside *schema*."""
    Base = _point_models_at_schema(schema)
    Base.metadata.create_all(bind=engine)


def ensure_first_superuser(engine: Engine, schema: str) -> bool:
    """
    Create the ``FIRST_SUPERUSER`` administrator when no user exists yet.

    Returns True when a user was created.  Existing databases (any row in
    ``users``) are left untouched, so this never overrides seeded or
    real accounts; the seed scripts keep ``admin@demo.com`` / ``Demo1234!``.
    """
    from sqlalchemy.orm import sessionmaker

    from backend.app.core.config import settings
    from backend.app.core.security import get_password_hash
    from backend.app.models.user import User, UserRole

    _point_models_at_schema(schema)
    Session = sessionmaker(bind=engine)
    session = Session()
    try:
        # `schema` comes from POSTGRES_SCHEMA / the environment, never from a
        # request, and an identifier cannot be a bind parameter; quote it
        # through the dialect so an odd schema name still cannot break out.
        quoted = engine.dialect.identifier_preparer.quote_schema(schema)
        search_path_sql = f"SET search_path TO {quoted}, public"
        # The suppression has to sit on the `text(...)` call, which is the node
        # semgrep reports; `fmt: skip` keeps the formatter from wrapping the
        # line and carrying the comment away from it.
        search_path = text(search_path_sql)  # nosemgrep: python.sqlalchemy.security.audit.avoid-sqlalchemy-text.avoid-sqlalchemy-text  # fmt: skip
        session.execute(search_path)
        if session.query(User.id).first() is not None:
            return False

        email = str(settings.FIRST_SUPERUSER).strip().lower()
        username = email.split("@", 1)[0] or "admin"
        user = User(
            username=username,
            email=email,
            full_name="Platform Admin",
            hashed_password=get_password_hash(settings.FIRST_SUPERUSER_PASSWORD),
            is_active=True,
            is_superuser=True,
            role=UserRole.ADMIN,
        )
        session.add(user)
        session.commit()
        logger.info("Created first superuser %s (role ADMIN)", email)
        return True
    finally:
        session.close()


# Every API replica runs the bootstrap on start-up (docker-entrypoint.sh).
# A blocking, session-level advisory lock serialises them: the first replica
# creates or upgrades the schema and the first administrator, the others wait
# and then find nothing left to do.  The key is derived from the schema name
# so two schemas in one database do not block each other.
BOOTSTRAP_LOCK_NAMESPACE = "experimently.bootstrap."


def _bootstrap_locked(engine: Engine, schema: str) -> str:
    cfg = alembic_config()

    ensure_schema(engine, schema)

    if has_alembic_version(engine, schema):
        logger.info(
            "alembic_version present in schema %s: running upgrade head", schema
        )
        command.upgrade(cfg, "head")
        result = "upgraded"
    else:
        logger.info(
            "Fresh database: creating schema %s from models and stamping head", schema
        )
        create_from_models(engine, schema)
        # env.py reads POSTGRES_SCHEMA for the alembic_version location.
        os.environ["POSTGRES_SCHEMA"] = schema
        command.stamp(cfg, "head")
        result = "created"

    ensure_first_superuser(engine, schema)
    return result


def bootstrap(engine: Engine | None = None, schema: str | None = None) -> str:
    """
    Bring the database up to date. Returns "upgraded" or "created".

    Safe to run concurrently from several processes (replicas): callers queue
    on a PostgreSQL advisory lock and run one after another.
    """
    schema = schema or schema_name()
    engine = engine or create_engine(database_url())
    lock_key = f"{BOOTSTRAP_LOCK_NAMESPACE}{schema}"

    # Dedicated autocommit connection: a session-level advisory lock is held
    # by this session until pg_advisory_unlock (or disconnect), independently
    # of the transactions alembic and create_all open on other connections.
    with engine.connect().execution_options(isolation_level="AUTOCOMMIT") as lock_conn:
        lock_conn.execute(
            text("SELECT pg_advisory_lock(hashtext(:key))"), {"key": lock_key}
        )
        logger.info("bootstrap: holding advisory lock %s", lock_key)
        try:
            return _bootstrap_locked(engine, schema)
        finally:
            lock_conn.execute(
                text("SELECT pg_advisory_unlock(hashtext(:key))"), {"key": lock_key}
            )


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    result = bootstrap()
    print(
        f"Database bootstrap complete ({result}) — schema '{schema_name()}' at {database_url().split('@')[-1]}"
    )
