"""
Bring a PostgreSQL database up to the current schema.

Two situations are handled:

* **Existing database** (has an ``alembic_version`` table): run
  ``alembic upgrade head`` so pending incremental migrations are applied.

* **Fresh database** (no ``alembic_version`` table): create the schema from
  the SQLAlchemy models with ``Base.metadata.create_all`` and then
  ``alembic stamp head``.  This is the pattern recommended in the Alembic
  cookbook ("Building an Up to Date Database from Scratch").  It is used
  because the historical migration chain in ``migrations/versions`` was
  autogenerated against databases that already had tables and cannot be
  replayed from zero (several revisions re-create tables that earlier
  revisions already created).  The models are the source of truth for the
  schema, exactly as they are for the test suite.

Usage (from the repository root)::

    python -m backend.app.db.bootstrap

Connection settings come from the usual ``POSTGRES_*`` environment
variables (``POSTGRES_SERVER``/``POSTGRES_HOST``, ``POSTGRES_PORT``,
``POSTGRES_USER``, ``POSTGRES_PASSWORD``, ``POSTGRES_DB``,
``POSTGRES_SCHEMA``).
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect
from sqlalchemy.engine import Engine
from sqlalchemy.schema import CreateSchema

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parents[3]
_ALEMBIC_INI = _REPO_ROOT / "backend" / "app" / "db" / "alembic.ini"
_MIGRATIONS_DIR = _REPO_ROOT / "backend" / "app" / "db" / "migrations"


def database_url() -> str:
    """Build a SQLAlchemy URL from the POSTGRES_* environment variables."""
    user = os.environ.get("POSTGRES_USER", "postgres")
    password = os.environ.get("POSTGRES_PASSWORD", "postgres")
    host = os.environ.get("POSTGRES_SERVER") or os.environ.get("POSTGRES_HOST") or "localhost"
    port = os.environ.get("POSTGRES_PORT", "5432")
    db = os.environ.get("POSTGRES_DB", "experimentation")
    return f"postgresql://{user}:{password}@{host}:{port}/{db}"


def schema_name() -> str:
    """Schema the application tables live in.

    ``POSTGRES_SCHEMA`` wins when set (this is what alembic's env.py uses);
    otherwise fall back to the application's own environment-derived choice
    so the bootstrap and the running app agree.
    """
    explicit = os.environ.get("POSTGRES_SCHEMA")
    if explicit:
        return explicit
    from backend.app.core.database_config import get_schema_name

    return get_schema_name()


def alembic_config() -> Config:
    """Alembic config that works regardless of the current working directory."""
    cfg = Config(str(_ALEMBIC_INI))
    cfg.set_main_option("script_location", str(_MIGRATIONS_DIR))
    return cfg


def ensure_schema(engine: Engine, schema: str) -> None:
    with engine.begin() as conn:
        conn.execute(CreateSchema(schema, if_not_exists=True))


def has_alembic_version(engine: Engine, schema: str) -> bool:
    return inspect(engine).has_table("alembic_version", schema=schema)


def create_from_models(engine: Engine, schema: str) -> None:
    """Create every table defined by the SQLAlchemy models inside *schema*."""
    # Importing the package registers all models on the shared metadata.
    import backend.app.models  # noqa: F401
    from backend.app.models.base import Base

    # Point every table at the requested schema (models.base.set_schema does
    # the same, but derives the name from APP_ENV rather than POSTGRES_SCHEMA).
    Base.metadata.schema = schema
    for table in Base.metadata.tables.values():
        table.schema = schema
    Base.metadata.create_all(bind=engine)


def bootstrap(engine: Engine | None = None, schema: str | None = None) -> str:
    """Bring the database up to date. Returns "upgraded" or "created"."""
    schema = schema or schema_name()
    engine = engine or create_engine(database_url())
    cfg = alembic_config()

    ensure_schema(engine, schema)

    if has_alembic_version(engine, schema):
        logger.info("alembic_version present in schema %s: running upgrade head", schema)
        command.upgrade(cfg, "head")
        return "upgraded"

    logger.info("Fresh database: creating schema %s from models and stamping head", schema)
    create_from_models(engine, schema)
    # env.py reads POSTGRES_SCHEMA for the alembic_version location.
    os.environ["POSTGRES_SCHEMA"] = schema
    command.stamp(cfg, "head")
    return "created"


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    result = bootstrap()
    print(f"Database bootstrap complete ({result}) — schema '{schema_name()}' at {database_url().split('@')[-1]}")
