apiVersion: v1
kind: Service
metadata:
  name: {{ include "experimently.fullname" . }}-api
  labels:
    {{- include "experimently.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "experimently.selectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
