"""Events: every stored ``created_at`` is rewritten to the canonical UTC string

``events.created_at`` is a VARCHAR, so every time window, ``ORDER BY`` and
``min()`` over events compares text.  Since #577 every new value is written in
one canonical form -- ``YYYY-MM-DDTHH:MM:SS+00:00``, or
``YYYY-MM-DDTHH:MM:SS.ffffff+00:00`` when there are microseconds -- but rows
stored before it keep the client's offset (``+02:00``), ``Z``, no offset at
all, a space separator or another fraction length, and those sort as text, not
as instants.  This revision rewrites each such value to the same instant in the
canonical form; a value with no offset is taken to be UTC, as the write path
does.  The DDL and the indexes do not change.  Nothing is imported from the
application: ``_normalise`` is a frozen copy of the string branch of
``backend.app.models.event.normalize_event_timestamp`` as of this revision
(``backend/tests/unit/db/test_events_created_at_utc_normaliser.py`` pins the
two equal).

How it runs, in order:

1. Offline (``--sql``) mode is refused: this is a data rewrite done in Python
   and cannot be emitted as SQL.
2. Everything else runs inside ``autocommit_block()``.  That commits the
   revisions before this one in the same ``upgrade heads`` run, with their
   ``alembic_version`` rows, so their locks (``users`` SHARE from
   ``d12cbd384bbe``, ``feature_flags`` ACCESS EXCLUSIVE from ``a89544fb1075``)
   are not held while events are rewritten; and each statement below commits
   on its own, so a batch holds its row locks only until its own commit.
3. For the session (``SET LOCAL`` means nothing in autocommit):
   ``lock_timeout`` is 30 s and ``search_path`` is the schema.  Both are put
   back to the values found, in ``finally`` (not ``RESET``, which would drop a
   value the session had set itself).  Setting the path is what lets every statement here be
   a fixed string.
4. One sequential scan copies the candidates into a temporary table, numbered
   in physical order: every value that does not already match the canonical
   pattern, plus the ones ending ``.000000+00:00`` (``_CANDIDATES``, which
   ``docs/self-hosting/migrations.md`` copies exactly).  The numbering is only
   for locality; rows are matched back by ``id``.  The table is dropped first
   if it exists, and always dropped in ``finally``.
5. Batches of 1,000.  Each value is normalised in Python.  A value the
   normaliser cannot read -- not ISO-8601, or a date out of range -- is left
   exactly as stored and counted.  Changed values are written with one
   ``UPDATE ... FROM unnest(...)`` per batch, whose ``WHERE`` also requires the
   stored value to be unchanged since the scan, so a row deleted or rewritten
   meanwhile is skipped.
6. One line is printed: how many values were rewritten, how many could not be
   read (with at most 20 event ids, never the stored text, which is client
   input and lands in a shared deploy log), and how long it took.

A run that stops part way (killed, timed out, a lock wait over 30 s) leaves the
earlier revisions applied and this one not recorded, with every finished batch
rewritten.  The next ``upgrade heads`` scans again and finishes the rest: the
rewrite is idempotent, because a rewritten value is canonical and is no longer
a candidate.

Core chain, extending the core head ``a89544fb1075`` (generated with
``revision --head a89544fb1075``; not autogenerated, as there is no DDL).
Nothing here touches a module table, so a full checkout still has exactly two
heads: this revision and ``modules_0002_warehouse_analysis``.

Revision ID: 1ab99332f0ba
Revises: a89544fb1075
Create Date: 2026-10-02
"""

import os
import sys
import time
from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ab99332f0ba"
down_revision: Union[str, None] = "a89544fb1075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The schema name comes from the deployment's own environment, never from a
# request.
_SCHEMA = os.environ.get("POSTGRES_SCHEMA", "experimentation")

_BATCH_SIZE = 1000
_MAX_IDS = 20

#: The candidate predicate.  ``docs/self-hosting/migrations.md`` copies it
#: character for character into the count an operator runs before and after
#: the upgrade, and ``_SCAN`` below spells it again (adjacent literals, so every
#: statement is one fixed string); the tests pin all three equal.  A value
#: that matches the pattern and does not end ``.000000+00:00`` is either
#: canonical already or unreadable either way, so it is never a candidate.
_CANDIDATES = (
    "created_at !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}"
    "(\\.[0-9]{6})?\\+00:00$'\n"
    "   OR created_at LIKE '%.000000+00:00'"
)

_SAVE = (
    "SELECT current_setting('lock_timeout') AS lock_timeout, "
    "current_setting('search_path') AS search_path"
)
_LOCK_TIMEOUT = "SET lock_timeout = '30s'"
_SEARCH_PATH = "SELECT set_config('search_path', quote_ident(:schema), false)"
_DROP = "DROP TABLE IF EXISTS pg_temp.event_created_at_rewrite"
_SCAN = (
    "CREATE TEMPORARY TABLE event_created_at_rewrite AS\n"
    "SELECT row_number() OVER (ORDER BY ctid) AS seq, id, created_at\n"
    "FROM events\n"
    "WHERE "
    "created_at !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}"
    "(\\.[0-9]{6})?\\+00:00$'\n"
    "   OR created_at LIKE '%.000000+00:00'"
)
_INDEX = "CREATE UNIQUE INDEX ON pg_temp.event_created_at_rewrite (seq)"
_BATCH = (
    "SELECT seq, id::text AS id, created_at "
    "FROM pg_temp.event_created_at_rewrite "
    "WHERE seq > :last ORDER BY seq LIMIT :size"
)
_UPDATE = (
    "UPDATE events AS e SET created_at = v.new "
    "FROM unnest(CAST(:ids AS uuid[]), CAST(:olds AS text[]), "
    "CAST(:news AS text[])) AS v(id, old, new) "
    "WHERE e.id = v.id AND e.created_at = v.old"
)
_RESTORE = (
    "SELECT set_config('lock_timeout', :lock_timeout, false), "
    "set_config('search_path', :search_path, false)"
)

_OFFLINE_REFUSAL = (
    "1ab99332f0ba rewrites events.created_at in Python and cannot be emitted "
    "as SQL; run it online (without --sql)."
)


def _normalise(value: str) -> str:
    """The string branch of ``normalize_event_timestamp``, frozen here.

    Raises ``ValueError`` for a value that is not ISO-8601 and
    ``OverflowError`` for one whose UTC instant falls outside the years
    1-9999; the caller counts both as unreadable.
    """
    moment = datetime.fromisoformat(value.strip())
    if moment.tzinfo is None:
        moment = moment.replace(tzinfo=timezone.utc)
    return moment.astimezone(timezone.utc).isoformat()


def _batch_done(number: int) -> None:
    """Called after each batch has been written.  Does nothing.

    A seam for the tests, which plant a pause or a failure here to look at the
    database part way through a run.
    """


def _report(rewritten: int, unreadable: int, ids: list, seconds: float) -> str:
    line = (
        f"{revision}: rewrote {rewritten} events.created_at values to UTC; "
        f"{unreadable} unreadable values left as stored"
    )
    if ids:
        more = unreadable - len(ids)
        line += f" (event ids: {', '.join(ids)}"
        line += f" and {more} more)" if more else ")"
    return f"{line}; {seconds:.1f} s"


def _rewrite(bind: sa.engine.Connection) -> str:
    started = time.monotonic()
    rewritten = unreadable = 0
    unreadable_ids: list = []
    found = dict(bind.execute(sa.text(_SAVE)).one()._mapping)
    try:
        bind.execute(sa.text(_LOCK_TIMEOUT))
        bind.execute(sa.text(_SEARCH_PATH), {"schema": _SCHEMA})
        bind.execute(sa.text(_DROP))
        bind.execute(sa.text(_SCAN))
        bind.execute(sa.text(_INDEX))

        last, batch = 0, 0
        while True:
            rows = bind.execute(
                sa.text(_BATCH), {"last": last, "size": _BATCH_SIZE}
            ).all()
            if not rows:
                break
            last = rows[-1].seq
            ids, olds, news = [], [], []
            for row in rows:
                try:
                    new = _normalise(row.created_at)
                except (ValueError, OverflowError):
                    unreadable += 1
                    if len(unreadable_ids) < _MAX_IDS:
                        unreadable_ids.append(row.id)
                    continue
                if new != row.created_at:
                    ids.append(row.id)
                    olds.append(row.created_at)
                    news.append(new)
            if ids:
                result = bind.execute(
                    sa.text(_UPDATE), {"ids": ids, "olds": olds, "news": news}
                )
                rewritten += result.rowcount
            batch += 1
            _batch_done(batch)
    finally:
        bind.execute(sa.text(_DROP))
        bind.execute(sa.text(_RESTORE), found)
    return _report(rewritten, unreadable, unreadable_ids, time.monotonic() - started)


def upgrade() -> None:
    if op.get_context().as_sql:
        raise RuntimeError(_OFFLINE_REFUSAL)
    with op.get_context().autocommit_block():
        line = _rewrite(op.get_bind())
    # On stdout, one line: alembic.ini's root logger is at WARN, so a logger
    # at INFO would be dropped outside alembic's own loggers.
    sys.stdout.write(line + "\n")
    sys.stdout.flush()


def downgrade() -> None:
    """A no-op: the original offsets cannot be restored.

    The upgrade kept each event's instant and dropped the offset the client
    sent with it.  Nothing recorded that offset, so there is nothing to put
    back.  Doing nothing is also right for the release before this one: it
    reads and writes exactly this format for the server's own timestamps, and
    the column type is unchanged.  To get the original text back, restore the
    snapshot taken before the upgrade.

    Downgrading to ``a89544fb1075`` and then running ``upgrade heads`` runs the
    rewrite again, which is how values written by an older release after the
    first run are rewritten (``docs/self-hosting/migrations.md``).
    """
