"""ep030_add_notification_tables

Revision ID: e181583b4b24
Revises: a1b2c3d4e5f6
Create Date: 2026-03-02 16:05:35.528396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e181583b4b24'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_delivery_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('SLACK', 'EMAIL', 'WEBHOOK', name='notification_channel'), nullable=False),
    sa.Column('recipient', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'SKIPPED', name='notification_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index(op.f('ix_experimentation_notification_delivery_log_created_at'), 'notification_delivery_log', ['created_at'], unique=False, schema='experimentation')
    op.create_index('ix_notif_log_created_at', 'notification_delivery_log', ['created_at'], unique=False, schema='experimentation')
    op.create_index('ix_notif_log_event_type', 'notification_delivery_log', ['event_type'], unique=False, schema='experimentation')
    op.create_index('ix_notif_log_status', 'notification_delivery_log', ['status'], unique=False, schema='experimentation')
    op.create_table('permissions',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index(op.f('ix_experimentation_permissions_created_at'), 'permissions', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_permissions_name'), 'permissions', ['name'], unique=True, schema='experimentation')
    op.create_index(op.f('ix_experimentation_permissions_resource'), 'permissions', ['resource'], unique=False, schema='experimentation')
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index(op.f('ix_experimentation_roles_created_at'), 'roles', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_roles_name'), 'roles', ['name'], unique=True, schema='experimentation')
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'DEVELOPER', 'VIEWER', name='userrole'), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    schema='experimentation'
    )
    op.create_index(op.f('ix_experimentation_users_created_at'), 'users', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_users_email'), 'users', ['email'], unique=True, schema='experimentation')
    op.create_index(op.f('ix_experimentation_users_username'), 'users', ['username'], unique=True, schema='experimentation')
    op.create_table('api_keys',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['experimentation.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index(op.f('ix_experimentation_api_keys_created_at'), 'api_keys', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_api_keys_key'), 'api_keys', ['key'], unique=True, schema='experimentation')
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['experimentation.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_audit_logs_action_type_idx', 'audit_logs', ['action_type'], unique=False, schema='experimentation')
    op.create_index('experimentation_audit_logs_entity_idx', 'audit_logs', ['entity_type', 'entity_id'], unique=False, schema='experimentation')
    op.create_index('experimentation_audit_logs_entity_timestamp_idx', 'audit_logs', ['entity_type', 'entity_id', 'timestamp'], unique=False, schema='experimentation')
    op.create_index('experimentation_audit_logs_timestamp_idx', 'audit_logs', ['timestamp'], unique=False, schema='experimentation', postgresql_using='btree')
    op.create_index('experimentation_audit_logs_user_id_idx', 'audit_logs', ['user_id'], unique=False, schema='experimentation')
    op.create_index('experimentation_audit_logs_user_timestamp_idx', 'audit_logs', ['user_id', 'timestamp'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='experimentation')
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('INACTIVE', 'ACTIVE', 'ARCHIVED', name='featureflagstatus'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('targeting_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rollout_percentage >= 0 AND rollout_percentage <= 100', name='check_rollout_percentage'),
    sa.ForeignKeyConstraint(['owner_id'], ['experimentation.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_feature_flag_owner_status', 'feature_flags', ['owner_id', 'status'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_feature_flags_created_at'), 'feature_flags', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_feature_flags_key'), 'feature_flags', ['key'], unique=True, schema='experimentation')
    op.create_index(op.f('ix_experimentation_feature_flags_status'), 'feature_flags', ['status'], unique=False, schema='experimentation')
    op.create_table('global_holdouts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('holdout_percentage', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('holdout_percentage >= 1 AND holdout_percentage <= 20', name='check_holdout_percentage_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['experimentation.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='experimentation'
    )
    op.create_index('experimentation_holdout_active', 'global_holdouts', ['is_active'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_global_holdouts_created_at'), 'global_holdouts', ['created_at'], unique=False, schema='experimentation')
    op.create_table('mutual_exclusion_groups',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('traffic_allocation', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='mutualexclusiongroupstatus'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('traffic_allocation >= 0.0 AND traffic_allocation <= 1.0', name='check_meg_traffic_allocation'),
    sa.ForeignKeyConstraint(['owner_id'], ['experimentation.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='experimentation'
    )
    op.create_index('experimentation_meg_status', 'mutual_exclusion_groups', ['status'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_mutual_exclusion_groups_created_at'), 'mutual_exclusion_groups', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_mutual_exclusion_groups_status'), 'mutual_exclusion_groups', ['status'], unique=False, schema='experimentation')
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notify_experiment_started', sa.Boolean(), nullable=False),
    sa.Column('notify_experiment_completed', sa.Boolean(), nullable=False),
    sa.Column('notify_safety_rollback', sa.Boolean(), nullable=False),
    sa.Column('notify_rollout_advanced', sa.Boolean(), nullable=False),
    sa.Column('slack_channel', sa.String(length=255), nullable=True),
    sa.Column('email_override', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['experimentation.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='experimentation'
    )
    op.create_index('ix_notif_pref_user_id', 'notification_preferences', ['user_id'], unique=False, schema='experimentation')
    op.create_table('role_permission_association',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['experimentation.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['experimentation.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='experimentation'
    )
    op.create_table('segments',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='segmentstatus'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['experimentation.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index(op.f('ix_experimentation_segments_created_at'), 'segments', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_segments_status'), 'segments', ['status'], unique=False, schema='experimentation')
    op.create_table('user_role_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['experimentation.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['experimentation.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='experimentation'
    )
    op.create_table('warehouse_connections',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('warehouse_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['experimentation.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('ix_experimentation_warehouse_conn_active', 'warehouse_connections', ['is_active'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_warehouse_connections_created_at'), 'warehouse_connections', ['created_at'], unique=False, schema='experimentation')
    op.create_table('aggregated_metrics',
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('feature_flag_id', sa.UUID(), nullable=True),
    sa.Column('targeting_rule_id', sa.String(length=255), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('sum_value', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('distinct_users', sa.Integer(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['experimentation.feature_flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['experimentation.segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_agg_metric_flag_period', 'aggregated_metrics', ['feature_flag_id', 'period', 'period_start'], unique=False, schema='experimentation')
    op.create_index('experimentation_agg_metric_period_time', 'aggregated_metrics', ['period', 'period_start'], unique=False, schema='experimentation')
    op.create_index('experimentation_agg_metric_unique', 'aggregated_metrics', ['metric_type', 'period', 'period_start', 'feature_flag_id', 'targeting_rule_id', 'segment_id'], unique=True, schema='experimentation')
    op.create_index(op.f('ix_experimentation_aggregated_metrics_created_at'), 'aggregated_metrics', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_aggregated_metrics_feature_flag_id'), 'aggregated_metrics', ['feature_flag_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_aggregated_metrics_metric_type'), 'aggregated_metrics', ['metric_type'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_aggregated_metrics_period'), 'aggregated_metrics', ['period'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_aggregated_metrics_period_start'), 'aggregated_metrics', ['period_start'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_aggregated_metrics_segment_id'), 'aggregated_metrics', ['segment_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_aggregated_metrics_targeting_rule_id'), 'aggregated_metrics', ['targeting_rule_id'], unique=False, schema='experimentation')
    op.create_table('error_logs',
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('feature_flag_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('stack_trace', sa.String(), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['experimentation.feature_flags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_error_flag_time', 'error_logs', ['feature_flag_id', 'timestamp'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_error_logs_created_at'), 'error_logs', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_error_logs_error_type'), 'error_logs', ['error_type'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_error_logs_feature_flag_id'), 'error_logs', ['feature_flag_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_error_logs_timestamp'), 'error_logs', ['timestamp'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_error_logs_user_id'), 'error_logs', ['user_id'], unique=False, schema='experimentation')
    op.create_table('experiments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='experimentstatus'), nullable=False),
    sa.Column('experiment_type', sa.Enum('A_B', 'MULTIVARIATE', 'SPLIT_URL', 'BANDIT', name='experimenttype'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('targeting_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimization_type', sa.Enum('fixed', 'thompson_sampling', 'ucb1', 'epsilon_greedy', name='optimization_type_enum'), nullable=False),
    sa.Column('sequential_testing_enabled', sa.Boolean(), nullable=False),
    sa.Column('sequential_testing_method', sa.Enum('msprt', 'always_valid', name='sequential_testing_method_enum'), nullable=True),
    sa.Column('sequential_testing_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variance_reduction_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mutual_exclusion_group_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date > start_date', name='check_experiment_dates'),
    sa.ForeignKeyConstraint(['mutual_exclusion_group_id'], ['experimentation.mutual_exclusion_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['experimentation.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_experiment_owner_status', 'experiments', ['owner_id', 'status'], unique=False, schema='experimentation')
    op.create_index('experimentation_experiment_status_dates', 'experiments', ['status', 'start_date', 'end_date'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_experiments_created_at'), 'experiments', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_experiments_status'), 'experiments', ['status'], unique=False, schema='experimentation')
    op.create_table('feature_flag_overrides',
    sa.Column('feature_flag_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['experimentation.feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_override_feature_user', 'feature_flag_overrides', ['feature_flag_id', 'user_id'], unique=True, schema='experimentation')
    op.create_index(op.f('ix_experimentation_feature_flag_overrides_created_at'), 'feature_flag_overrides', ['created_at'], unique=False, schema='experimentation')
    op.create_table('raw_metrics',
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('feature_flag_id', sa.UUID(), nullable=True),
    sa.Column('targeting_rule_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['experimentation.feature_flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['experimentation.segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_raw_metric_flag_time', 'raw_metrics', ['feature_flag_id', 'timestamp'], unique=False, schema='experimentation')
    op.create_index('experimentation_raw_metric_user_flag', 'raw_metrics', ['user_id', 'feature_flag_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_raw_metrics_created_at'), 'raw_metrics', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_raw_metrics_feature_flag_id'), 'raw_metrics', ['feature_flag_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_raw_metrics_metric_type'), 'raw_metrics', ['metric_type'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_raw_metrics_segment_id'), 'raw_metrics', ['segment_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_raw_metrics_targeting_rule_id'), 'raw_metrics', ['targeting_rule_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_raw_metrics_timestamp'), 'raw_metrics', ['timestamp'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_raw_metrics_user_id'), 'raw_metrics', ['user_id'], unique=False, schema='experimentation')
    op.create_table('rollout_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('feature_flag_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='rolloutschedulestatus'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_percentage', sa.Integer(), nullable=False),
    sa.Column('min_stage_duration', sa.Integer(), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date > start_date', name='check_rollout_schedule_dates'),
    sa.CheckConstraint('max_percentage >= 0 AND max_percentage <= 100', name='check_max_percentage'),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['experimentation.feature_flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['experimentation.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_rollout_schedule_flag_status', 'rollout_schedules', ['feature_flag_id', 'status'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_rollout_schedules_status'), 'rollout_schedules', ['status'], unique=False, schema='experimentation')
    op.create_table('bandit_states',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('variant_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_pulls', sa.Integer(), nullable=False),
    sa.Column('regret_reduction_pct', sa.Float(), nullable=True),
    sa.Column('last_computed_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experimentation.experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id'),
    schema='experimentation'
    )
    op.create_index('experimentation_bandit_state_exp_id', 'bandit_states', ['experiment_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_bandit_states_created_at'), 'bandit_states', ['created_at'], unique=False, schema='experimentation')
    op.create_table('metrics',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.Enum('CONVERSION', 'REVENUE', 'COUNT', 'DURATION', 'CUSTOM', name='metrictype'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('aggregation_method', sa.String(length=50), nullable=True),
    sa.Column('minimum_sample_size', sa.Integer(), nullable=True),
    sa.Column('expected_effect', sa.Float(), nullable=True),
    sa.Column('event_value_path', sa.String(length=100), nullable=True),
    sa.Column('lower_is_better', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experimentation.experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_metric_experiment_event', 'metrics', ['experiment_id', 'event_name'], unique=False, schema='experimentation')
    op.create_index('experimentation_metric_experiment_name', 'metrics', ['experiment_id', 'name'], unique=True, schema='experimentation')
    op.create_index(op.f('ix_experimentation_metrics_created_at'), 'metrics', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_metrics_event_name'), 'metrics', ['event_name'], unique=False, schema='experimentation')
    op.create_table('rollout_stages',
    sa.Column('rollout_schedule_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('target_percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='rolloutstagestatus'), nullable=False),
    sa.Column('trigger_type', sa.Enum('TIME_BASED', 'METRIC_BASED', 'MANUAL', name='triggertype'), nullable=False),
    sa.Column('trigger_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('target_percentage >= 0 AND target_percentage <= 100', name='check_target_percentage'),
    sa.ForeignKeyConstraint(['rollout_schedule_id'], ['experimentation.rollout_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_rollout_stage_schedule', 'rollout_stages', ['rollout_schedule_id', 'stage_order'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_rollout_stages_created_at'), 'rollout_stages', ['created_at'], unique=False, schema='experimentation')
    op.create_table('variants',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_control', sa.Boolean(), nullable=True),
    sa.Column('traffic_allocation', sa.Integer(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('traffic_allocation >= 0 AND traffic_allocation <= 100', name='check_traffic_allocation'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experimentation.experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_variant_experiment', 'variants', ['experiment_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_variants_created_at'), 'variants', ['created_at'], unique=False, schema='experimentation')
    op.create_table('assignments',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experimentation.experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['experimentation.variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_assignment_experiment_user', 'assignments', ['experiment_id', 'user_id'], unique=True, schema='experimentation')
    op.create_index('experimentation_assignment_user', 'assignments', ['user_id'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_assignments_created_at'), 'assignments', ['created_at'], unique=False, schema='experimentation')
    op.create_table('events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=True),
    sa.Column('feature_flag_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experimentation.experiments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['experimentation.feature_flags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['experimentation.variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='experimentation'
    )
    op.create_index('experimentation_event_experiment_timestamp', 'events', ['experiment_id', 'created_at'], unique=False, schema='experimentation')
    op.create_index('experimentation_event_experiment_type', 'events', ['experiment_id', 'event_type'], unique=False, schema='experimentation')
    op.create_index('experimentation_event_feature_flag_type', 'events', ['feature_flag_id', 'event_type'], unique=False, schema='experimentation')
    op.create_index('experimentation_event_user_type', 'events', ['user_id', 'event_type'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_events_created_at'), 'events', ['created_at'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_events_event_name'), 'events', ['event_name'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_events_event_type'), 'events', ['event_type'], unique=False, schema='experimentation')
    op.create_index(op.f('ix_experimentation_events_user_id'), 'events', ['user_id'], unique=False, schema='experimentation')
    op.drop_table('role_permission_association')
    op.drop_table('user_role_association')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('user_role_association',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['experimentation.roles.id'], name='user_role_association_role_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['experimentation.users.id'], name='user_role_association_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_role_association_pkey')
    )
    op.create_table('role_permission_association',
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['experimentation.permissions.id'], name='role_permission_association_permission_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['experimentation.roles.id'], name='role_permission_association_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='role_permission_association_pkey')
    )
    op.drop_index(op.f('ix_experimentation_events_user_id'), table_name='events', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_events_event_type'), table_name='events', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_events_event_name'), table_name='events', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_events_created_at'), table_name='events', schema='experimentation')
    op.drop_index('experimentation_event_user_type', table_name='events', schema='experimentation')
    op.drop_index('experimentation_event_feature_flag_type', table_name='events', schema='experimentation')
    op.drop_index('experimentation_event_experiment_type', table_name='events', schema='experimentation')
    op.drop_index('experimentation_event_experiment_timestamp', table_name='events', schema='experimentation')
    op.drop_table('events', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_assignments_created_at'), table_name='assignments', schema='experimentation')
    op.drop_index('experimentation_assignment_user', table_name='assignments', schema='experimentation')
    op.drop_index('experimentation_assignment_experiment_user', table_name='assignments', schema='experimentation')
    op.drop_table('assignments', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_variants_created_at'), table_name='variants', schema='experimentation')
    op.drop_index('experimentation_variant_experiment', table_name='variants', schema='experimentation')
    op.drop_table('variants', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_rollout_stages_created_at'), table_name='rollout_stages', schema='experimentation')
    op.drop_index('experimentation_rollout_stage_schedule', table_name='rollout_stages', schema='experimentation')
    op.drop_table('rollout_stages', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_metrics_event_name'), table_name='metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_metrics_created_at'), table_name='metrics', schema='experimentation')
    op.drop_index('experimentation_metric_experiment_name', table_name='metrics', schema='experimentation')
    op.drop_index('experimentation_metric_experiment_event', table_name='metrics', schema='experimentation')
    op.drop_table('metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_bandit_states_created_at'), table_name='bandit_states', schema='experimentation')
    op.drop_index('experimentation_bandit_state_exp_id', table_name='bandit_states', schema='experimentation')
    op.drop_table('bandit_states', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_rollout_schedules_status'), table_name='rollout_schedules', schema='experimentation')
    op.drop_index('experimentation_rollout_schedule_flag_status', table_name='rollout_schedules', schema='experimentation')
    op.drop_table('rollout_schedules', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_raw_metrics_user_id'), table_name='raw_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_raw_metrics_timestamp'), table_name='raw_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_raw_metrics_targeting_rule_id'), table_name='raw_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_raw_metrics_segment_id'), table_name='raw_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_raw_metrics_metric_type'), table_name='raw_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_raw_metrics_feature_flag_id'), table_name='raw_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_raw_metrics_created_at'), table_name='raw_metrics', schema='experimentation')
    op.drop_index('experimentation_raw_metric_user_flag', table_name='raw_metrics', schema='experimentation')
    op.drop_index('experimentation_raw_metric_flag_time', table_name='raw_metrics', schema='experimentation')
    op.drop_table('raw_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_feature_flag_overrides_created_at'), table_name='feature_flag_overrides', schema='experimentation')
    op.drop_index('experimentation_override_feature_user', table_name='feature_flag_overrides', schema='experimentation')
    op.drop_table('feature_flag_overrides', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_experiments_status'), table_name='experiments', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_experiments_created_at'), table_name='experiments', schema='experimentation')
    op.drop_index('experimentation_experiment_status_dates', table_name='experiments', schema='experimentation')
    op.drop_index('experimentation_experiment_owner_status', table_name='experiments', schema='experimentation')
    op.drop_table('experiments', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_error_logs_user_id'), table_name='error_logs', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_error_logs_timestamp'), table_name='error_logs', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_error_logs_feature_flag_id'), table_name='error_logs', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_error_logs_error_type'), table_name='error_logs', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_error_logs_created_at'), table_name='error_logs', schema='experimentation')
    op.drop_index('experimentation_error_flag_time', table_name='error_logs', schema='experimentation')
    op.drop_table('error_logs', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_aggregated_metrics_targeting_rule_id'), table_name='aggregated_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_aggregated_metrics_segment_id'), table_name='aggregated_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_aggregated_metrics_period_start'), table_name='aggregated_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_aggregated_metrics_period'), table_name='aggregated_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_aggregated_metrics_metric_type'), table_name='aggregated_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_aggregated_metrics_feature_flag_id'), table_name='aggregated_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_aggregated_metrics_created_at'), table_name='aggregated_metrics', schema='experimentation')
    op.drop_index('experimentation_agg_metric_unique', table_name='aggregated_metrics', schema='experimentation')
    op.drop_index('experimentation_agg_metric_period_time', table_name='aggregated_metrics', schema='experimentation')
    op.drop_index('experimentation_agg_metric_flag_period', table_name='aggregated_metrics', schema='experimentation')
    op.drop_table('aggregated_metrics', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_warehouse_connections_created_at'), table_name='warehouse_connections', schema='experimentation')
    op.drop_index('ix_experimentation_warehouse_conn_active', table_name='warehouse_connections', schema='experimentation')
    op.drop_table('warehouse_connections', schema='experimentation')
    op.drop_table('user_role_association', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_segments_status'), table_name='segments', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_segments_created_at'), table_name='segments', schema='experimentation')
    op.drop_table('segments', schema='experimentation')
    op.drop_table('role_permission_association', schema='experimentation')
    op.drop_index('ix_notif_pref_user_id', table_name='notification_preferences', schema='experimentation')
    op.drop_table('notification_preferences', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_mutual_exclusion_groups_status'), table_name='mutual_exclusion_groups', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_mutual_exclusion_groups_created_at'), table_name='mutual_exclusion_groups', schema='experimentation')
    op.drop_index('experimentation_meg_status', table_name='mutual_exclusion_groups', schema='experimentation')
    op.drop_table('mutual_exclusion_groups', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_global_holdouts_created_at'), table_name='global_holdouts', schema='experimentation')
    op.drop_index('experimentation_holdout_active', table_name='global_holdouts', schema='experimentation')
    op.drop_table('global_holdouts', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_feature_flags_status'), table_name='feature_flags', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_feature_flags_key'), table_name='feature_flags', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_feature_flags_created_at'), table_name='feature_flags', schema='experimentation')
    op.drop_index('experimentation_feature_flag_owner_status', table_name='feature_flags', schema='experimentation')
    op.drop_table('feature_flags', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_audit_logs_created_at'), table_name='audit_logs', schema='experimentation')
    op.drop_index('experimentation_audit_logs_user_timestamp_idx', table_name='audit_logs', schema='experimentation')
    op.drop_index('experimentation_audit_logs_user_id_idx', table_name='audit_logs', schema='experimentation')
    op.drop_index('experimentation_audit_logs_timestamp_idx', table_name='audit_logs', schema='experimentation', postgresql_using='btree')
    op.drop_index('experimentation_audit_logs_entity_timestamp_idx', table_name='audit_logs', schema='experimentation')
    op.drop_index('experimentation_audit_logs_entity_idx', table_name='audit_logs', schema='experimentation')
    op.drop_index('experimentation_audit_logs_action_type_idx', table_name='audit_logs', schema='experimentation')
    op.drop_table('audit_logs', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_api_keys_key'), table_name='api_keys', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_api_keys_created_at'), table_name='api_keys', schema='experimentation')
    op.drop_table('api_keys', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_users_username'), table_name='users', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_users_email'), table_name='users', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_users_created_at'), table_name='users', schema='experimentation')
    op.drop_table('users', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_roles_name'), table_name='roles', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_roles_created_at'), table_name='roles', schema='experimentation')
    op.drop_table('roles', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_permissions_resource'), table_name='permissions', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_permissions_name'), table_name='permissions', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_permissions_created_at'), table_name='permissions', schema='experimentation')
    op.drop_table('permissions', schema='experimentation')
    op.drop_index('ix_notif_log_status', table_name='notification_delivery_log', schema='experimentation')
    op.drop_index('ix_notif_log_event_type', table_name='notification_delivery_log', schema='experimentation')
    op.drop_index('ix_notif_log_created_at', table_name='notification_delivery_log', schema='experimentation')
    op.drop_index(op.f('ix_experimentation_notification_delivery_log_created_at'), table_name='notification_delivery_log', schema='experimentation')
    op.drop_table('notification_delivery_log', schema='experimentation')
    # ### end Alembic commands ###
