#!/usr/bin/env python3
"""The IAM actions the deploy workflows' OIDC role needs, derived from their text.

    python3 scripts/iam_actions.py --check    # the committed copies are current
    python3 scripts/iam_actions.py --write    # regenerate them

Sources (PE v1 C12): `.github/workflows/{deploy,rollback,db-migrate}.yml`,
every `.github/actions/**/action.yml`, every file under `scripts/` those
workflows or actions run, and `STAGED_SCRIPTS` (scripts the role will run that
no workflow names yet). Each `aws <service> <verb>` in them becomes an IAM
action; `docker push`/`docker pull` and the ECR login action add the registry
actions they need; `register-task-definition` and `run-task` add
`iam:PassRole` (scoped to ECS tasks in the policy).

Two committed copies are generated, never hand-edited:

* `infrastructure/cdk/github-actions-deploy-policy.json` -- the permissions
  policy for the workflow role (one per environment, same document);
* the table between the GENERATED markers in
  `docs/deployment/iam-permissions.md`.

A call the map below does not know fails generation: a new AWS service in a
workflow cannot slip into the role unexamined. `--check` is run by
`backend/tests/unit/infrastructure/test_iam_actions.py`.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = [
    REPO_ROOT / ".github" / "workflows" / name
    for name in ("deploy.yml", "rollback.yml", "db-migrate.yml")
]
ACTIONS_DIR = REPO_ROOT / ".github" / "actions"
#: Scripts the workflow role will run that no workflow names yet. The role's
#: policy is applied by a person in every account (D7) before the first deploy
#: that needs it, so a script is granted when it lands, not when it is wired:
#: `ecs_rolling_rollout.sh` is C4c's, and C4 wires it into deploy.yml and
#: rollback.yml. Once a workflow names it, its entry here is redundant.
STAGED_SCRIPTS = [REPO_ROOT / "scripts" / "ecs_rolling_rollout.sh"]
POLICY = REPO_ROOT / "infrastructure" / "cdk" / "github-actions-deploy-policy.json"
DOC = REPO_ROOT / "docs" / "deployment" / "iam-permissions.md"
BEGIN = "<!-- BEGIN GENERATED by scripts/iam_actions.py; do not edit by hand -->"
END = "<!-- END GENERATED -->"

#: CLI service name -> IAM service prefix.
SERVICES = {
    "cloudformation": "cloudformation",
    "deploy": "codedeploy",
    "ecr": "ecr",
    "ecs": "ecs",
    "elbv2": "elasticloadbalancing",
    "logs": "logs",
    "rds": "rds",
    "secretsmanager": "secretsmanager",
    "sts": "sts",
}

#: Calls whose IAM action is not the verb in PascalCase.
SPECIAL = {
    ("ecr", "get-login-password"): ["ecr:GetAuthorizationToken"],
    # "No permissions are required to perform this operation."
    ("sts", "get-caller-identity"): [],
    # Waiters poll a describe call.
    ("ecs", "wait tasks-stopped"): ["ecs:DescribeTasks"],
    ("ecs", "wait services-stable"): ["ecs:DescribeServices"],
    ("rds", "wait db-cluster-snapshot-available"): ["rds:DescribeDBClusterSnapshots"],
    ("deploy", "wait deployment-successful"): ["codedeploy:GetDeployment"],
}

#: What a call needs beyond its own action.
IMPLIED = {
    # The task definition names an execution role (and the API's a task
    # role); registering or running it passes them to ECS.
    ("ecs", "register-task-definition"): ["iam:PassRole"],
    ("ecs", "run-task"): ["iam:PassRole"],
    # An AppSpecContent revision is registered and its deployment config read
    # as part of creating the deployment.
    ("deploy", "create-deployment"): [
        "codedeploy:GetDeploymentConfig",
        "codedeploy:RegisterApplicationRevision",
    ],
}

#: Non-`aws` operations that need registry permissions.
DOCKER = {
    "docker push": [
        "ecr:BatchCheckLayerAvailability",
        "ecr:CompleteLayerUpload",
        "ecr:InitiateLayerUpload",
        "ecr:PutImage",
        "ecr:UploadLayerPart",
    ],
    "docker pull": [
        "ecr:BatchCheckLayerAvailability",
        "ecr:BatchGetImage",
        "ecr:GetDownloadUrlForLayer",
    ],
}
ACTION_USES = {
    "aws-actions/amazon-ecr-login": ["ecr:GetAuthorizationToken"],
}

_AWS = re.compile(r"\baws\s+([a-z0-9-]+)\s+(wait\s+[a-z0-9-]+|[a-z0-9-]+)")
_SCRIPT = re.compile(r"\bscripts/[A-Za-z0-9_./-]+\.(?:sh|py)\b")
_PY_OPERATION = re.compile(r'\(\s*"([a-z0-9-]+)",\s*"([a-z0-9-]+)"\s*\)')


def _pascal(verb: str) -> str:
    return "".join(
        "DB" if part == "db" else part.capitalize() for part in verb.split("-")
    )


def iam_actions_for(service: str, verb: str) -> list[str]:
    verb = re.sub(r"\s+", " ", verb)
    if service not in SERVICES:
        raise SystemExit(
            f"aws {service} {verb}: the CLI service {service!r} is not mapped to an "
            "IAM prefix in scripts/iam_actions.py; add it deliberately"
        )
    if (service, verb) in SPECIAL:
        base = SPECIAL[(service, verb)]
    elif verb.startswith("wait "):
        raise SystemExit(f"aws {service} {verb}: map this waiter in SPECIAL")
    else:
        base = [f"{SERVICES[service]}:{_pascal(verb)}"]
    return base + IMPLIED.get((service, verb), [])


def _code(script: str) -> str:
    return "\n".join(
        ln for ln in script.splitlines() if not ln.lstrip().startswith("#")
    )


def _yaml_steps(path: Path) -> list[dict]:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if "jobs" in document:
        return [s for job in document["jobs"].values() for s in job.get("steps", [])]
    return document.get("runs", {}).get("steps", [])


def sources() -> list[Path]:
    """The workflows, every local action, and the scripts either one runs."""
    files = [
        *WORKFLOWS,
        *sorted(ACTIONS_DIR.glob("**/action.yml")),
        *STAGED_SCRIPTS,
    ]
    seen: list[Path] = []
    queue = list(files)
    while queue:
        path = queue.pop(0)
        if path in seen:
            continue
        seen.append(path)
        text = path.read_text(encoding="utf-8")
        if path.suffix == ".yml":
            text = "\n".join(_code(s["run"]) for s in _yaml_steps(path) if "run" in s)
        for match in _SCRIPT.findall(_code(text)):
            script = REPO_ROOT / match
            if not script.is_file():
                raise SystemExit(
                    f"{path.relative_to(REPO_ROOT)} runs {match}, which does not exist"
                )
            queue.append(script)
    return seen


def _join_continuations(text: str) -> str:
    """Fold shell line continuations, so `aws ecs \\` + `update-service` is one call.

    Without this the split form -- the usual shape of a long call -- matched
    nothing, and the call's action was simply absent from the role.
    """
    return re.sub(r"\\[ \t]*\r?\n[ \t]*", " ", text)


def calls(paths: list[Path] | None = None) -> dict[str, set[str]]:
    """IAM action -> the places (file: call) that need it."""
    found: dict[str, set[str]] = defaultdict(set)
    for path in sources() if paths is None else paths:
        try:
            where = str(path.relative_to(REPO_ROOT))
        except ValueError:
            where = str(path)
        if path.suffix == ".yml":
            steps = _yaml_steps(path)
            text = "\n".join(_code(s["run"]) for s in steps if "run" in s)
            for step in steps:
                uses = str(step.get("uses", "")).split("@")[0]
                for action in ACTION_USES.get(uses, []):
                    found[action].add(f"{where}: uses {uses}")
        else:
            text = _code(path.read_text(encoding="utf-8"))
            if path.suffix == ".py":
                for service, verb in _PY_OPERATION.findall(text):
                    if service in SERVICES:
                        for action in iam_actions_for(service, verb):
                            found[action].add(f"{where}: aws {service} {verb}")
        text = _join_continuations(text)
        for service, verb in _AWS.findall(text):
            for action in iam_actions_for(service, verb):
                found[action].add(f"{where}: aws {service} {re.sub(r' +', ' ', verb)}")
        for command, actions in DOCKER.items():
            if command in text:
                for action in actions:
                    found[action].add(f"{where}: {command}")
    return found


def policy(found: dict[str, set[str]]) -> dict:
    actions = sorted(a for a in found if a != "iam:PassRole")
    statements = [
        {
            "Sid": "DeployWorkflows",
            "Effect": "Allow",
            "Action": actions,
            "Resource": "*",
        }
    ]
    if "iam:PassRole" in found:
        statements.append(
            {
                "Sid": "PassTaskRolesToEcs",
                "Effect": "Allow",
                "Action": "iam:PassRole",
                "Resource": "*",
                "Condition": {
                    "StringEquals": {"iam:PassedToService": "ecs-tasks.amazonaws.com"}
                },
            }
        )
    return {"Version": "2012-10-17", "Statement": statements}


def table(found: dict[str, set[str]]) -> str:
    rows = ["| Action | Needed by |", "|---|---|"]
    for action in sorted(found):
        places = "<br>".join(f"`{p}`" for p in sorted(found[action]))
        rows.append(f"| `{action}` | {places} |")
    return "\n".join(rows)


def _doc_with(block: str) -> str:
    text = DOC.read_text(encoding="utf-8")
    start, end = text.index(BEGIN) + len(BEGIN), text.index(END)
    return text[:start] + "\n" + block + "\n" + text[end:]


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--print", action="store_true")
    args = parser.parse_args(argv)

    found = calls()
    policy_text = json.dumps(policy(found), indent=2) + "\n"
    doc_text = _doc_with(table(found))
    if args.print:
        print(policy_text)
        print(table(found))
        return 0
    if args.write:
        POLICY.write_text(policy_text, encoding="utf-8")
        DOC.write_text(doc_text, encoding="utf-8")
        return 0
    stale = [
        str(path.relative_to(REPO_ROOT))
        for path, expected in ((POLICY, policy_text), (DOC, doc_text))
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
    if stale:
        print(
            "::error::out of date with the workflows: "
            + ", ".join(stale)
            + ". Run `python3 scripts/iam_actions.py --write` and review the diff: "
            "every added action is one more thing the deploy role may do."
        )
        return 1
    print(f"{len(found)} actions; the policy and the documented table are current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
