#!/usr/bin/env python3
"""The IAM actions the deploy workflows' OIDC role needs, derived from their text.

    python3 scripts/iam_actions.py --check    # the committed copies are current
    python3 scripts/iam_actions.py --write    # regenerate them

Sources (PE v1 C12): `.github/workflows/{deploy,rollback,db-migrate}.yml`,
every `.github/actions/**/action.yml`, every file under `scripts/` those
workflows or actions run, every sibling module such a Python script imports,
and `STAGED_SCRIPTS` (scripts the role will run that no workflow names yet).
Each `aws <service> <verb>` in them becomes an IAM
action; `docker push`/`docker pull` and the ECR login action add the registry
actions they need; `IMPLIED` adds the actions AWS checks behind a call
without the call naming them -- `register-task-definition` and `run-task`
add `iam:PassRole` (scoped to ECS tasks in the policy) and
`create-db-cluster-snapshot` adds `rds:AddTagsToResource` (scoped to cluster
snapshots, #744); and a flag in
`FLAG_IMPLIED`, in the same `run:` block or script as its call, adds the
action that flag needs (`create-deployment --override-alarm-configuration`
needs `codedeploy:UpdateDeploymentGroup`).

Two committed copies are generated, never hand-edited:

* `infrastructure/cdk/github-actions-deploy-policy.json` -- the permissions
  policy for the workflow role (one per environment, same document);
* the table between the GENERATED markers in
  `docs/deployment/iam-permissions.md`.

A call the map below does not know fails generation: a new AWS service in a
workflow cannot slip into the role unexamined. `--check` is run by
`backend/tests/unit/infrastructure/test_iam_actions.py`.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = [
    REPO_ROOT / ".github" / "workflows" / name
    for name in ("deploy.yml", "rollback.yml", "db-migrate.yml")
]
ACTIONS_DIR = REPO_ROOT / ".github" / "actions"
#: Scripts the workflow role will run that no workflow names yet. The role's
#: policy is applied by a person in every account (D7) before the first deploy
#: that needs it, so a script is granted when it lands, not when it is wired.
#: Once a workflow names it, its entry must go (a test fails until it does):
#: `ecs_rolling_rollout.sh` was staged here until deploy.yml and rollback.yml
#: ran it (#69).
STAGED_SCRIPTS: list[Path] = []
POLICY = REPO_ROOT / "infrastructure" / "cdk" / "github-actions-deploy-policy.json"
DOC = REPO_ROOT / "docs" / "deployment" / "iam-permissions.md"
BEGIN = "<!-- BEGIN GENERATED by scripts/iam_actions.py; do not edit by hand -->"
END = "<!-- END GENERATED -->"

#: CLI service name -> IAM service prefix.
SERVICES = {
    "cloudformation": "cloudformation",
    "cloudwatch": "cloudwatch",
    "deploy": "codedeploy",
    "ecr": "ecr",
    "ecs": "ecs",
    "elbv2": "elasticloadbalancing",
    "logs": "logs",
    "rds": "rds",
    "secretsmanager": "secretsmanager",
    "sts": "sts",
}

#: Calls whose IAM action is not the verb in PascalCase.
SPECIAL = {
    ("ecr", "get-login-password"): ["ecr:GetAuthorizationToken"],
    # "No permissions are required to perform this operation."
    ("sts", "get-caller-identity"): [],
    # Waiters poll a describe call.
    ("ecs", "wait tasks-stopped"): ["ecs:DescribeTasks"],
    ("ecs", "wait services-stable"): ["ecs:DescribeServices"],
    ("rds", "wait db-cluster-snapshot-available"): ["rds:DescribeDBClusterSnapshots"],
    ("deploy", "wait deployment-successful"): ["codedeploy:GetDeployment"],
}

#: What a call needs beyond its own action: the actions AWS checks implicitly,
#: which no `aws` command in the sources names (#744). The scan reads commands,
#: so an action AWS authorizes behind one is invisible to it; this table is the
#: only place such an action enters the role, and each entry cites where AWS
#: documents it. The machine-readable source for all of them is the
#: "AuthorizedActions" of the operation in
#: https://servicereference.us-east-1.amazonaws.com/v1/<prefix>/<prefix>.json
#: (the Service Authorization Reference's "API operations" table).
#:
#: That list also names actions an operation checks only conditionally. Each
#: one below was audited against how the sources call the operation, and
#: these are deliberately absent, because the condition never holds here:
#:   ecs register-task-definition, run-task -> ecs:TagResource: only when the
#:     request carries tags. register_task_definition.sh sends
#:     `describe-task-definition --query taskDefinition`, which has no tags,
#:     and no run-task passes --tags or --propagate-tags.
#:   ecs update-service -> iam:PassRole: only for a role set on the service
#:     (EBS volume or Service Connect TLS roles); ecs_rolling_rollout.sh
#:     changes only the task definition.
#:   deploy continue-deployment, stop-deployment ->
#:     codedeploy:CreateCloudFormationDeployment: CloudFormation-driven
#:     blue/green only; these deployments are ECS ones created directly.
#:   cloudformation describe-stacks -> cloudformation:ListStacks: only without
#:     a stack name; stack-outputs always passes --stack-name.
#:   ecr batch-get-image, get-download-url-for-layer ->
#:     ecr:BatchImportUpstreamImage, ecr:CreateRepository, ecr:TagResource:
#:     pull-through cache only; the deploy pulls from its own repository.
#:   logs get-log-events -> logs:Unmask: only with --unmask.
IMPLIED = {
    # The task definition names an execution role (and the API's a task
    # role); registering or running it passes them to ECS.
    # https://docs.aws.amazon.com/service-authorization/latest/reference/list_ecs.html#list_ecs-operations
    ("ecs", "register-task-definition"): ["iam:PassRole"],
    ("ecs", "run-task"): ["iam:PassRole"],
    # "When you specify CreateDeployment permissions, you must also specify
    # GetDeploymentConfig permissions for the deployment configuration and
    # GetApplicationRevision or RegisterApplicationRevision permissions for
    # the application revision."
    # https://docs.aws.amazon.com/codedeploy/latest/userguide/auth-and-access-control-permissions-reference.html
    # That sentence reads as either-or, and RegisterApplicationRevision alone
    # was granted until #754. Observed in the staging rollback rehearsal: its
    # create-deployment, sending an AppSpec for a revision that had been
    # deployed before (the previous task definition), was refused with "not
    # authorized to perform: codedeploy:GetApplicationRevision"; the deploys'
    # create-deployment calls, with an AppSpec for a new revision, were not.
    # So both are granted. The service reference lists both among
    # CreateDeployment's AuthorizedActions:
    # https://docs.aws.amazon.com/service-authorization/latest/reference/list_codedeploy.html#list_codedeploy-operations
    # Both are scoped to the application resource type; like
    # RegisterApplicationRevision, it is granted on `*` with the rest.
    ("deploy", "create-deployment"): [
        "codedeploy:GetApplicationRevision",
        "codedeploy:GetDeploymentConfig",
        "codedeploy:RegisterApplicationRevision",
    ],
    # The CDK's Aurora cluster copies its tags to every snapshot, and AWS
    # authorizes that copy as rds:AddTagsToResource on the new snapshot. The
    # first staging deploy was refused at "Snapshot the database before
    # migrating" without it: "not authorized to perform: rds:AddTagsToResource
    # on resource: arn:aws:rds:...:cluster-snapshot:...".
    # https://docs.aws.amazon.com/service-authorization/latest/reference/list_rds.html#list_rds-operations
    # (CreateDBClusterSnapshot -> rds:AddTagsToResource, rds:CreateDBClusterSnapshot)
    ("rds", "create-db-cluster-snapshot"): ["rds:AddTagsToResource"],
}

#: An implied action granted only on the resources the implying call creates,
#: in a statement of its own, instead of on `*` with the rest. Tagging is
#: needed on the snapshot the deploy takes, not on every RDS resource.
SCOPED = {
    "rds:AddTagsToResource": (
        "TagClusterSnapshots",
        "arn:aws:rds:*:*:cluster-snapshot:*",
    ),
}

#: What a call needs because of a FLAG it is given (#148). The generator used
#: to read verbs only, so adding a flag with its own permission kept the gate
#: green while the role lacked it. A flag counts when it is in the same `run:`
#: block (or script) as the call, not only on the same line: deploy.yml adds
#: the alarm override to its create-deployment through an array, under the
#: break-glass input.
FLAG_IMPLIED = {
    # "To override alarm configurations, you need the UpdateDeploymentGroup
    # IAM permission when calling CreateDeployment" (the CLI's own help).
    ("deploy", "create-deployment", "--override-alarm-configuration"): [
        "codedeploy:UpdateDeploymentGroup"
    ],
}

#: Non-`aws` operations that need registry permissions.
DOCKER = {
    "docker push": [
        "ecr:BatchCheckLayerAvailability",
        "ecr:CompleteLayerUpload",
        "ecr:InitiateLayerUpload",
        "ecr:PutImage",
        "ecr:UploadLayerPart",
    ],
    "docker pull": [
        "ecr:BatchCheckLayerAvailability",
        "ecr:BatchGetImage",
        "ecr:GetDownloadUrlForLayer",
    ],
}
ACTION_USES = {
    "aws-actions/amazon-ecr-login": ["ecr:GetAuthorizationToken"],
}

_AWS = re.compile(r"\baws\s+([a-z0-9-]+)\s+(wait\s+[a-z0-9-]+|[a-z0-9-]+)")
_SCRIPT = re.compile(r"\bscripts/[A-Za-z0-9_./-]+\.(?:sh|py)\b")
_PY_OPERATION = re.compile(r'\(\s*"([a-z0-9-]+)",\s*"([a-z0-9-]+)"\s*\)')
#: A top-level `import x` / `from x import ...` in a script. When `x.py` sits
#: beside it, that module's calls are the script's calls: shift_traffic.py
#: reaches AWS through api_serving.py and check_live_target_group.py.
_PY_IMPORT = re.compile(r"^(?:import|from)\s+([A-Za-z_][A-Za-z0-9_]*)", re.M)


def _pascal(verb: str) -> str:
    return "".join(
        "DB" if part == "db" else part.capitalize() for part in verb.split("-")
    )


def iam_actions_for(service: str, verb: str) -> list[str]:
    verb = re.sub(r"\s+", " ", verb)
    if service not in SERVICES:
        raise SystemExit(
            f"aws {service} {verb}: the CLI service {service!r} is not mapped to an "
            "IAM prefix in scripts/iam_actions.py; add it deliberately"
        )
    if (service, verb) in SPECIAL:
        base = SPECIAL[(service, verb)]
    elif verb.startswith("wait "):
        raise SystemExit(f"aws {service} {verb}: map this waiter in SPECIAL")
    else:
        base = [f"{SERVICES[service]}:{_pascal(verb)}"]
    return base + IMPLIED.get((service, verb), [])


def _code(script: str) -> str:
    return "\n".join(
        ln for ln in script.splitlines() if not ln.lstrip().startswith("#")
    )


def _yaml_steps(path: Path) -> list[dict]:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if "jobs" in document:
        return [s for job in document["jobs"].values() for s in job.get("steps", [])]
    return document.get("runs", {}).get("steps", [])


def sources() -> list[Path]:
    """The workflows, every local action, and the scripts either one runs."""
    files = [
        *WORKFLOWS,
        *sorted(ACTIONS_DIR.glob("**/action.yml")),
        *STAGED_SCRIPTS,
    ]
    seen: list[Path] = []
    queue = list(files)
    while queue:
        path = queue.pop(0)
        if path in seen:
            continue
        seen.append(path)
        text = path.read_text(encoding="utf-8")
        if path.suffix == ".yml":
            text = "\n".join(_code(s["run"]) for s in _yaml_steps(path) if "run" in s)
        for match in _SCRIPT.findall(_code(text)):
            script = REPO_ROOT / match
            if not script.is_file():
                raise SystemExit(
                    f"{path.relative_to(REPO_ROOT)} runs {match}, which does not exist"
                )
            queue.append(script)
        if path.suffix == ".py":
            for name in _PY_IMPORT.findall(text):
                sibling = path.parent / f"{name}.py"
                if sibling.is_file():
                    queue.append(sibling)
    return seen


def declared_operations(source: str) -> set[tuple[str, str]]:
    """The `(service, verb)` pairs a script's module-level `OPERATIONS` lists."""
    pairs: set[tuple[str, str]] = set()
    for node in ast.parse(source).body:
        targets = node.targets if isinstance(node, ast.Assign) else []
        if not any(isinstance(t, ast.Name) and t.id == "OPERATIONS" for t in targets):
            continue
        for item in ast.walk(node.value):
            if (
                isinstance(item, ast.Tuple)
                and len(item.elts) == 2
                and all(
                    isinstance(e, ast.Constant) and isinstance(e.value, str)
                    for e in item.elts
                )
            ):
                pairs.add((item.elts[0].value, item.elts[1].value))
    return pairs


def _check_declared_operations(path: Path) -> None:
    """A script's `OPERATIONS` allow-list is its AWS calls: every service in it
    must be mapped. The tuple scan below skips unmapped services, because
    scripts hold other string pairs (`("blue", "green")`); without this, an
    operation on a new service was dropped from the role in silence (#297:
    `("cloudwatch", "describe-alarms")` was, until `cloudwatch` was mapped).
    """
    for service, verb in sorted(declared_operations(path.read_text(encoding="utf-8"))):
        if service not in SERVICES:
            raise SystemExit(
                f"{path.name}: OPERATIONS lists aws {service} {verb}, and the CLI "
                f"service {service!r} is not mapped to an IAM prefix in "
                "scripts/iam_actions.py; add it deliberately"
            )


def _join_continuations(text: str) -> str:
    """Fold shell line continuations, so `aws ecs \\` + `update-service` is one call.

    Without this the split form -- the usual shape of a long call -- matched
    nothing, and the call's action was simply absent from the role.
    """
    return re.sub(r"\\[ \t]*\r?\n[ \t]*", " ", text)


def _flag_implied(block: str, where: str, found: dict[str, set[str]]) -> None:
    """Add FLAG_IMPLIED's actions for each (call, flag) that share `block`."""
    block = _join_continuations(block)
    called = {(s, re.sub(r"\s+", " ", v)) for s, v in _AWS.findall(block)}
    for (service, verb, flag), actions in FLAG_IMPLIED.items():
        if (service, verb) in called and re.search(
            rf"(?<![\w-]){re.escape(flag)}(?![\w-])", block
        ):
            for action in actions:
                found[action].add(f"{where}: aws {service} {verb} {flag}")


def calls(paths: list[Path] | None = None) -> dict[str, set[str]]:
    """IAM action -> the places (file: call) that need it."""
    found: dict[str, set[str]] = defaultdict(set)
    for path in sources() if paths is None else paths:
        try:
            where = str(path.relative_to(REPO_ROOT))
        except ValueError:
            where = str(path)
        if path.suffix == ".yml":
            steps = _yaml_steps(path)
            for step in steps:
                if "run" in step:
                    _flag_implied(_code(step["run"]), where, found)
            text = "\n".join(_code(s["run"]) for s in steps if "run" in s)
            for step in steps:
                uses = str(step.get("uses", "")).split("@")[0]
                for action in ACTION_USES.get(uses, []):
                    found[action].add(f"{where}: uses {uses}")
        else:
            text = _code(path.read_text(encoding="utf-8"))
            _flag_implied(text, where, found)
            if path.suffix == ".py":
                _check_declared_operations(path)
                for service, verb in _PY_OPERATION.findall(text):
                    if service in SERVICES:
                        for action in iam_actions_for(service, verb):
                            found[action].add(f"{where}: aws {service} {verb}")
        text = _join_continuations(text)
        for service, verb in _AWS.findall(text):
            for action in iam_actions_for(service, verb):
                found[action].add(f"{where}: aws {service} {re.sub(r' +', ' ', verb)}")
        for command, actions in DOCKER.items():
            if command in text:
                for action in actions:
                    found[action].add(f"{where}: {command}")
    return found


def policy(found: dict[str, set[str]]) -> dict:
    actions = sorted(a for a in found if a != "iam:PassRole" and a not in SCOPED)
    statements = [
        {
            "Sid": "DeployWorkflows",
            "Effect": "Allow",
            "Action": actions,
            "Resource": "*",
        }
    ]
    for action, (sid, resource) in sorted(SCOPED.items()):
        if action in found:
            statements.append(
                {"Sid": sid, "Effect": "Allow", "Action": action, "Resource": resource}
            )
    if "iam:PassRole" in found:
        statements.append(
            {
                "Sid": "PassTaskRolesToEcs",
                "Effect": "Allow",
                "Action": "iam:PassRole",
                "Resource": "*",
                "Condition": {
                    "StringEquals": {"iam:PassedToService": "ecs-tasks.amazonaws.com"}
                },
            }
        )
    return {"Version": "2012-10-17", "Statement": statements}


def table(found: dict[str, set[str]]) -> str:
    rows = ["| Action | Needed by |", "|---|---|"]
    for action in sorted(found):
        places = "<br>".join(f"`{p}`" for p in sorted(found[action]))
        rows.append(f"| `{action}` | {places} |")
    return "\n".join(rows)


def _doc_with(block: str) -> str:
    text = DOC.read_text(encoding="utf-8")
    start, end = text.index(BEGIN) + len(BEGIN), text.index(END)
    return text[:start] + "\n" + block + "\n" + text[end:]


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--print", action="store_true")
    args = parser.parse_args(argv)

    found = calls()
    policy_text = json.dumps(policy(found), indent=2) + "\n"
    doc_text = _doc_with(table(found))
    if args.print:
        print(policy_text)
        print(table(found))
        return 0
    if args.write:
        POLICY.write_text(policy_text, encoding="utf-8")
        DOC.write_text(doc_text, encoding="utf-8")
        return 0
    stale = [
        str(path.relative_to(REPO_ROOT))
        for path, expected in ((POLICY, policy_text), (DOC, doc_text))
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
    if stale:
        print(
            "::error::out of date with the workflows: "
            + ", ".join(stale)
            + ". Run `python3 scripts/iam_actions.py --write` and review the diff: "
            "every added action is one more thing the deploy role may do."
        )
        return 1
    print(f"{len(found)} actions; the policy and the documented table are current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
