/**
 * Cross-SDK hash parity tests for the React Native SDK.
 *
 * Test vectors are generated by the Python reference implementation and
 * verified against the Java, Go, iOS (Swift), Android (Kotlin), and
 * Flutter (Dart) SDKs.
 *
 * All SDKs must produce identical hash outputs for the same inputs.
 */

import { hashUser } from '../src/evaluator';

describe('hashUser — cross-SDK parity', () => {
  /**
   * Known test vectors (Python reference):
   *   hashlib.md5(f'{userId}:{flagKey}'.encode()).digest()[:4]
   *   → struct.unpack('<I', ...)[0] / 4294967296.0
   */
  const VECTORS: Array<[string, string, number]> = [
    ['user-123', 'my-flag',       0.6927449859213],
    ['user-456', 'feature-x',     0.0776851554],
    ['alice',    'dark-mode',     0.0353864399],
    ['bob',      'new-checkout',  0.1463384565],
    ['user-789', 'beta-feature',  0.3134219283],
    ['test-user','flag-key',      0.9923393740],
    ['',         'empty-user',    0.3582690393],
    ['a',        'b',             0.6056532171],
  ];

  test.each(VECTORS)(
    'hashUser(%s, %s) ≈ %f',
    (userId, flagKey, expected) => {
      expect(hashUser(userId, flagKey)).toBeCloseTo(expected, 7);
    }
  );
});

describe('hashUser — divisor correctness', () => {
  test('divisor is 2^32 (4294967296) not MaxUInt32 (4294967295)', () => {
    // user-123:my-flag → MD5 first-4-bytes little-endian uint32 = 2975317059
    //   / 4294967296 = 0.692744985921308   ← correct
    //   / 4294967295 = 0.692744986082601   ← wrong (differs at 9th decimal)
    const result = hashUser('user-123', 'my-flag');

    // Correct value matches 2^32 divisor to 12 significant figures.
    expect(result).toBeCloseTo(0.692744985921308, 11);

    // If the wrong divisor were used, result would be ~1.61e-10 larger.
    // We verify result < 0.69274498610 (which would catch the wrong divisor).
    expect(result).toBeLessThan(0.69274498610);
  });

  test('hash is always in [0.0, 1.0)', () => {
    const cases = [
      ['user-0', 'flag-0'],
      ['', ''],
      ['very-long-user-id-with-lots-of-chars', 'very-long-flag-key-name'],
      ['unicode-\u00e9', 'flag'],
    ];
    for (const [uid, fk] of cases) {
      const h = hashUser(uid, fk);
      expect(h).toBeGreaterThanOrEqualTo(0);
      expect(h).toBeLessThan(1);
    }
  });

  test('separator is colon between userId and flagKey', () => {
    // The concatenation format is "{userId}:{flagKey}"
    // user-123:my-flag → known hash
    expect(hashUser('user-123', 'my-flag')).toBeCloseTo(0.6927449859, 7);
  });

  test('different inputs produce different hashes', () => {
    const h1 = hashUser('user-A', 'flag-x');
    const h2 = hashUser('user-B', 'flag-x');
    const h3 = hashUser('user-A', 'flag-y');
    expect(h1).not.toBeCloseTo(h2, 10);
    expect(h1).not.toBeCloseTo(h3, 10);
  });

  test('hash is deterministic — same inputs always return same value', () => {
    for (let i = 0; i < 20; i++) {
      expect(hashUser('stable-user', 'stable-flag')).toBeCloseTo(
        hashUser('stable-user', 'stable-flag'),
        15
      );
    }
  });

  test('little-endian byte order produces the correct known value', () => {
    // If big-endian byte order were used, the result would differ significantly.
    // The known-correct little-endian result for user-123:my-flag is 0.6927449859.
    expect(hashUser('user-123', 'my-flag')).toBeCloseTo(0.6927449859, 7);
  });
});
