/**
 * The browser calculator must agree with the server's.
 *
 * `frontend/src/utils/power.ts` is a transcription of
 * `backend/app/services/power_calculator_service.py`. A transcription drifts
 * unless something pins it, so these vectors were GENERATED by calling the
 * Python service, not typed from the formula:
 *
 *   PowerCalculatorService().compute_sample_size(
 *       baseline_rate=..., minimum_detectable_effect=..., alpha=..., power=...,
 *       n_variants=...).per_variant
 *
 * If the server's formula changes, these fail and someone has to decide
 * whether the browser follows. That is the point: they are not decoration, and
 * an "approximately equal" assertion would defeat it, so the sample sizes are
 * compared EXACTLY. Both sides take a ceiling, so exactness is achievable and
 * any disagreement in the normal quantile shows up as an off-by-one rather
 * than hiding inside a tolerance.
 */
import {
  computeSampleSize,
  computePowerCurve,
  normPpf,
  normCdf,
} from '@/utils/power';

describe('normPpf matches scipy.stats.norm.ppf', () => {
  // scipy.stats.norm.ppf(p) to 10 significant figures.
  it.each([
    [0.975, 1.959963985],
    [0.95, 1.644853627],
    [0.99, 2.326347874],
    [0.995, 2.575829304],
    [0.8, 0.8416212336],
    [0.9, 1.281551566],
    [0.5, 0.0],
    [0.025, -1.959963985],
  ])('ppf(%s) ≈ %s', (p, expected) => {
    expect(normPpf(p as number)).toBeCloseTo(expected as number, 7);
  });

  it('rejects a probability outside (0, 1) rather than returning Infinity', () => {
    expect(() => normPpf(0)).toThrow(RangeError);
    expect(() => normPpf(1)).toThrow(RangeError);
  });

  it('is the inverse of the CDF', () => {
    for (const p of [0.01, 0.1, 0.3, 0.5, 0.7, 0.9, 0.99]) {
      expect(normCdf(normPpf(p))).toBeCloseTo(p, 6);
    }
  });
});

describe('computeSampleSize matches the Python service exactly', () => {
  // GENERATED by running PowerCalculatorService, not hand-computed.
  it.each([
    // baseline, mde,  alpha, power, variants, perVariant, total
    [0.05, 0.10, 0.05, 0.8, 2, 31234, 62468],
    [0.05, 0.10, 0.05, 0.8, 4, 41661, 166644],
    [0.2, 0.05, 0.01, 0.9, 2, 48497, 96994],
    [0.5, 0.2, 0.05, 0.95, 3, 745, 2235],
    [0.01, 0.5, 0.05, 0.8, 2, 7750, 15500],
  ])(
    'p=%s mde=%s alpha=%s power=%s k=%s -> %s per variant',
    (baselineRate, mde, alpha, power, nVariants, perVariant, total) => {
      const r = computeSampleSize({
        baselineRate: baselineRate as number,
        mde: mde as number,
        alpha: alpha as number,
        power: power as number,
        nVariants: nVariants as number,
      });
      expect(r.per_variant).toBe(perVariant);
      expect(r.total).toBe(total);
    },
  );

  it('applies the Bonferroni correction over k-1 comparisons', () => {
    // The only difference between these is the variant count, and more
    // variants must require MORE per variant, not fewer.
    const two = computeSampleSize({ baselineRate: 0.05, mde: 0.1, nVariants: 2 });
    const four = computeSampleSize({ baselineRate: 0.05, mde: 0.1, nVariants: 4 });
    expect(four.per_variant).toBeGreaterThan(two.per_variant);
    expect(four.corrected_alpha).toBeCloseTo(0.05 / 3, 12);
  });

  it('computes a runtime only when daily traffic is given', () => {
    const without = computeSampleSize({ baselineRate: 0.05, mde: 0.1 });
    expect(without.runtime_days).toBeNull();

    const with_ = computeSampleSize({
      baselineRate: 0.05, mde: 0.1, dailyTraffic: 10000, trafficAllocation: 1.0,
    });
    // 31234 per variant, 2 variants, 10000/day -> 5000 per variant per day
    expect(with_.runtime_days).toBeCloseTo(31234 / 5000, 6);
  });

  it('rejects inputs the server rejects, rather than returning NaN', () => {
    expect(() => computeSampleSize({ baselineRate: 0, mde: 0.1 })).toThrow(RangeError);
    expect(() => computeSampleSize({ baselineRate: 1, mde: 0.1 })).toThrow(RangeError);
    expect(() => computeSampleSize({ baselineRate: 0.05, mde: 0 })).toThrow(RangeError);
    expect(() => computeSampleSize({ baselineRate: 0.05, mde: 0.1, alpha: 0.6 })).toThrow(RangeError);
    expect(() => computeSampleSize({ baselineRate: 0.05, mde: 0.1, power: 1 })).toThrow(RangeError);
    expect(() => computeSampleSize({ baselineRate: 0.05, mde: 0.1, nVariants: 1 })).toThrow(RangeError);
    expect(() =>
      computeSampleSize({ baselineRate: 0.5, mde: 0.1, metricType: 'mean' }),
    ).toThrow(RangeError);
  });
});

describe('computePowerCurve', () => {
  it('returns points that decrease as the effect grows', () => {
    const pts = computePowerCurve({ baselineRate: 0.05 });
    expect(pts.length).toBeGreaterThan(10);
    for (let i = 1; i < pts.length; i += 1) {
      expect(pts[i].sample_size_per_variant).toBeLessThanOrEqual(pts[i - 1].sample_size_per_variant);
    }
  });

  it('agrees with computeSampleSize at each point', () => {
    const pts = computePowerCurve({ baselineRate: 0.05, points: 5 });
    for (const p of pts) {
      const direct = computeSampleSize({ baselineRate: 0.05, mde: p.effect_size_relative });
      expect(p.sample_size_per_variant).toBe(direct.per_variant);
    }
  });

  it('drops points it cannot compute instead of throwing', () => {
    // A baseline of 0.9 with a 50% relative lift puts the treatment past 1.
    const pts = computePowerCurve({ baselineRate: 0.9, minEffect: 0.01, maxEffect: 0.5 });
    expect(pts.length).toBeGreaterThan(0);
    expect(pts.every((p) => Number.isFinite(p.sample_size_per_variant))).toBe(true);
  });
});
